In [1]:
import sys

print(sys.executable)

E:\CAROLA\CAROLA TRABAJO\PASANTIA UNNE - AGENTE ASUNTOS LEGALES\pasantia-segem-agentes-ia\.venv\Scripts\python.exe

In [6]:
import sys
import subprocess

subprocess.check_call([
    sys.executable,
    "-m",
    "pip",
    "install",
    "pandas",
    "beautifulsoup4",
    "lxml",
    "html5lib",
    "ftfy",
    "unidecode",
    "markdownify",
    "tqdm"
])

0

# 01 - Exploración inicial de CSV y JSON

Objetivo: entender la estructura inicial de los archivos entregados para la pasantía.

En esta etapa vamos a responder:

- Cuántos registros hay.
- Qué columnas/campos tiene cada archivo.
- Dónde podría estar el texto legal del oficio/embargo.
- Si hay HTML dentro del texto.
- Si hay valores nulos.
- Si hay documentos repetidos.
- Si hay tipos de documento.
- Si hay respuestas generadas.

# 1. Verificar entorno y rutas

Primera celda de código:

In [9]:
import sys
from pathlib import Path

print("Python ejecutándose desde:")
print(sys.executable)

Python ejecutándose desde:
E:\CAROLA\CAROLA TRABAJO\PASANTIA UNNE - AGENTE ASUNTOS LEGALES\pasantia-segem-agentes-ia\.venv\Scripts\python.exe

In [10]:
PROJECT_ROOT = Path.cwd().parent

RAW_DIR = PROJECT_ROOT / "data" / "raw"
PROCESSED_DIR = PROJECT_ROOT / "data" / "processed"

print("Proyecto:", PROJECT_ROOT)
print("Raw:", RAW_DIR)
print("Processed:", PROCESSED_DIR)

print("Existe data/raw:", RAW_DIR.exists())
print("Existe data/processed:", PROCESSED_DIR.exists())

Proyecto: E:\CAROLA\CAROLA TRABAJO\PASANTIA UNNE - AGENTE ASUNTOS LEGALES\pasantia-segem-agentes-ia
Raw: E:\CAROLA\CAROLA TRABAJO\PASANTIA UNNE - AGENTE ASUNTOS LEGALES\pasantia-segem-agentes-ia\data\raw
Processed: E:\CAROLA\CAROLA TRABAJO\PASANTIA UNNE - AGENTE ASUNTOS LEGALES\pasantia-segem-agentes-ia\data\processed
Existe data/raw: True
Existe data/processed: True

# 2. Imports principales

In [11]:
import pandas as pd
import json
import re
from bs4 import BeautifulSoup
from IPython.display import display

print("Librerías importadas correctamente")
print("Pandas:", pd.__version__)

Librerías importadas correctamente
Pandas: 3.0.3

# 3. Ver qué archivos hay en data/raw

In [12]:
archivos_raw = list(RAW_DIR.iterdir())

print("Archivos encontrados en data/raw:")
for archivo in archivos_raw:
    print("-", archivo.name)

Archivos encontrados en data/raw:
- Entradas origen drive.csv
- Entradas origen drive.json

# 4. Definir nombres de archivos

In [14]:
csv_path = RAW_DIR / "Entradas origen drive.csv"
json_path = RAW_DIR / "Entradas origen drive.json"

print("CSV existe:", csv_path.exists())
print("JSON existe:", json_path.exists())

CSV existe: True
JSON existe: True

# 5. Cargar CSV

In [15]:
df_csv = pd.read_csv(csv_path)

print("CSV cargado correctamente")
print("Filas y columnas:", df_csv.shape)

CSV cargado correctamente
Filas y columnas: (2986, 4)

# 6. Ver primeras filas del CSV

In [16]:
df_csv.head()
df_csv.tail()

,id,texto_ocr,nombre,clasificacion
2981,547398,Error al enviar al textify.,Solicitud de informacion de usuarios,Oficio
2982,547399,20 MAR 2026\n\ngr\nRE ERAS duniciaL REITERATOR...,Embargo - usuario,Embargo
2983,547401,Poder Judicial de la Nación\nJUZGADO CIVIL 29\...,Embargo - usuario,Embargo
2984,547402,Poder Judicial de la Nación\n\nÑ PEL\n\nCédula...,Demanda,Juicio
2985,547403,Error al descargar el archivo desde el bucket.,Demanda,Juicio

# 7. Ver columnas del CSV

In [17]:
columnas_csv = df_csv.columns.tolist()

print("Cantidad de columnas:", len(columnas_csv))
print("Columnas del CSV:")

for col in columnas_csv:
    print("-", col)

Cantidad de columnas: 4
Columnas del CSV:
- id
- texto_ocr
- nombre
- clasificacion

# 8. Información general del CSV

In [18]:
df_csv.info()

<class 'pandas.DataFrame'>
RangeIndex: 2986 entries, 0 to 2985
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             2986 non-null   int64
 1   texto_ocr      2986 non-null   str
 2   nombre         2986 non-null   str
 3   clasificacion  2986 non-null   str
dtypes: int64(1), str(3)
memory usage: 93.4 KB

# 9. Valores nulos por columna

In [19]:
nulos_csv = df_csv.isna().sum().sort_values(ascending=False)

nulos_csv

id               0
texto_ocr        0
nombre           0
clasificacion    0
dtype: int64

## Versión más linda en tabla:

In [20]:
reporte_nulos_csv = pd.DataFrame({
    "columna": df_csv.columns,
    "nulos": df_csv.isna().sum().values,
    "porcentaje_nulos": (df_csv.isna().mean().values * 100).round(2)
}).sort_values(by="nulos", ascending=False)

display(reporte_nulos_csv)

         columna  nulos  porcentaje_nulos
0             id      0               0.0
1      texto_ocr      0               0.0
2         nombre      0               0.0
3  clasificacion      0               0.0

# 10. Detectar columnas de texto largo en CSV

In [24]:
def analizar_columnas_texto(df):
    resultados = []

    for col in df.columns:
        serie_original = df[col].dropna()

        if len(serie_original) == 0:
            continue

        # Convertimos a texto para poder medir largo, aunque pandas no la haya detectado como object
        serie = serie_original.astype(str)
        largos = serie.str.len()

        resultados.append({
            "columna": col,
            "tipo_dato": str(df[col].dtype),
            "valores_no_nulos": int(serie.count()),
            "promedio_caracteres": round(largos.mean(), 2),
            "max_caracteres": int(largos.max()),
            "min_caracteres": int(largos.min())
        })

    if len(resultados) == 0:
        print("No se encontraron columnas con datos para analizar.")
        return pd.DataFrame()

    return pd.DataFrame(resultados).sort_values(
        by="promedio_caracteres",
        ascending=False
    )

In [25]:
reporte_texto_csv = analizar_columnas_texto(df_csv)

display(reporte_texto_csv)

,columna,tipo_dato,valores_no_nulos,promedio_caracteres,max_caracteres,min_caracteres
1,texto_ocr,str,2986,3287.25,117897,1
2,nombre,str,2986,18.33,49,5
3,clasificacion,str,2986,9.46,18,5
0,id,int64,2986,6.00,6,6

# 11. Ver ejemplos de columnas candidatas
Después de ver el reporte, elegí una columna candidata.  

Por ejemplo, si aparece una columna llamada body, texto, descripcion, html, documento, content, etc.

In [26]:
COLUMNA_TEXTO_CSV = "texto_ocr"

for i, texto in enumerate(df_csv[COLUMNA_TEXTO_CSV].dropna().astype(str).head(5), start=1):
    print("=" * 100)
    print(f"EJEMPLO CSV {i}")
    print("=" * 100)
    print(texto[:3000])
    print()

====================================================================================================
EJEMPLO CSV 1
====================================================================================================
ii
4373-350
o.gestona.profesionalU gmail.com

A A A A

Tel:

FEDERAL

MERCADO PAGI

toría Profesional
21 011 - 4373-3500

lor a profesional) gmail.com

AE isaoss s326 MXN ÍN
DO Bo

0.4
Poder Judicial de la Nación

JUZGADO CIVIL 53

OFICIO. CON FIRMA ELECTRÓNICA CONFORME
ACORDADA 12/2020 C.S.JN (para cotejo de certificado de
validación de firma, descargar documento en: consulta de causas
en www.pjn.gov.ar//consulta de causas/ jurisdicción: cámara

nacional en lo civil// número de expediente// año).

mercado
libre OFICIO
ENE 2026 EMBARGO
pi
EPCION Buenos Aires, de diciembre de 2025

Mercado Pago Servicios de procesamiento S.R.L.
Avenida Caseros nro. 3039 piso 2 de CABA.

S / D:

Tengo el agrado de dirigirme a Usted en los autos
caratulados “LA VICTORIA POLO COUNTRY CLUB S.A. e/
RAMIREZ, MATIAS s/COBRO DE SUMAS DE DINERO”
EXP. 12611/2025 en trámite por ante el Juzgado Nacional de
Primera Instancia CIVIL NRO. 53, sito en Avenida de los
Inmigrantes nro. 1950 PISO 6 de CABA a cargo del Dr. DAMIAN
ESTEBAN VENTURA, secretaría única a mi cargo, en el que se
dispuso librar el presente a los fines que trabe embargo
preventivo por la suma de Pesos tres millones seiscientos ochenta
y siete mil novecientos ochenta y nueve con cincuenta y tres
centavos ($ 3.687.989,53-) en concepto de capital, con más la
suma de pesos cinca millones ($ 5.000.000-), que se
presupuestan provisoriamente para responder a intereses y
costas, sobre los fondos que en cualquier concepto pertenezcan a
Matías Gustavo Ramírez DNI nro. 37.249.466, en Mercado

Pago.

Poder Judicial de la Nación
JUZGADO CIVIL 53

Las sumas embargadas deberán depositarse en la cuenta
judicial abierta a nombre de autos y a la orden de este Juzgado,
cuyos datos son: Sucursal Cta.: 0089 — TRIBUNALES; Cuenta
Nro: 9995551635; C.B.U.: 0110025950099955516354.

Se hace saber que la contestación deberá ser brindada en un
único archivo "PDF" a la casilla del tribunal (
jncivil53Opjn.gov.ar), consignando el numero y caratula del
presente oficio.

El auto que ordena y autoriza el presente dice en su parte
pertinente: “Buenos Aires, 17 de noviembre de 2025..... Fecho,
atento lo solicitado, estado de las actuaciones, y conforme lo
previsto por el 212, inc. 2”, del Código Procesal, trábese por la
suma de pesos tres millones seiscientos embargo preventivo
ochenta y siete mil novecientos ochenta y nueve con cincuenta y
tres centavos ($ 3.687.989,53-) de pesos cinco millones en
concepto de capital, con más la suma (8 5.000.000-) , que se
presupuestan provisoriamente para responder a intereses y costas,
sobre los fondos que en cualquier concepto pertenezcan a Matías
Gustavo Ramírez en Mercado Pago, debiéndose depositar los
(DNI n* 37.249.466) importes resultantes en el Banco de la
Nación Argentina -Sucursal Tribunales-, en la cuenta abierta a
nombre de autos y como perteneciente a este Juzgado. A tal fin,
líbrese oficio, dejándose constancia de las personas autorizadas
para correr con el diligenciamiento...FDO. DAMIÁN ESTEBAN
V

====================================================================================================
EJEMPLO CSV 2
====================================================================================================
R

012 E

ercado Poder Judicial de la Nación

JUZGADO CIVIL 6

OFICIO JUDICIAL DE EMBARGO.-

Buenos Aires, de diciembre de 2025.

A MERCADOLIBRE S.R.L.
S / D

Tengo el agrado de dirigirme a Uds., en
los autos caratulados: “KATRIP, IVANA SOLEDAD C/
CAVALLI, PABLO FERNANDO S/ DAÑOS Y
PERJUICIOS” (EXPTE. N* 57435/2020), en trámite ante el
Juzgado Nacional de Primera Instancia en lo Civil N* 6, a mi
cargo, Secretaría Única, a cargo de la Dra. Oddi, Mariela, sito en
Avda. de Inmigrantes 1950, Piso 4? de la Ciudad Autónoma de
Buenos Aires, con el objeto de que se sirva disponer lo necesario
para trabar embargo sobre los fondos que el demandado Sr.
PABLO FERNANDO CAVALLI (CUIT N” 20-22351060-5)
tenga depositados en MERCADOLIBRE S.R.L. en el presente
o que se depositen en el futuro, hasta cubrir la suma de $279,331
,06, en concepto de capital de condena con más la suma de
$200.000,00 que se calcula provisionalmente para responder a
intereses y costas.

Se hace saber que deberá informar al Juzgado
el resultado de la gestión encomendada.

Los importes retenidos deberán ser
transferidos al Banco de la Nación Argentina, Sucursal
Tribunales, Cuenta N* 9990944541 - CBU N?
0110025950099909445419, a la orden de este Juzgado y como
pertenecientes a este juicio.

Como recaudo se transcribe el auto que ordena
la medida y que en su parte pertinente dice: “Buenos Aires, 29
de agosto de 2025.- JRR I.- Téngase por iniciada la ejecución de
sentencia por la actora: En atención a lo solicitado, sentencia
de fs. 359/399 digitales, liquidación practicada a fs. 436/437
digitales, que fuera aprobada a fs. 440 digitales, hasta cubrir la
suma de $279.331,06 con más la suma de $ 200.000 que

provisoriamente se presupuesta para responder a intereses y

“echa de firma: 29
MÁ

Firmado pi

20/2025

IÑLA ooh],

Ss

"RETARIO DE JUZGADO

rostas, trábese embargo sobre los fondos pertenecientes al
demandado Pablo Fernando Cavalli (CUIT N* 20 -22351060
15) en MERCADOLIBRE S.R.L.; los que deberán ser
iransferidos al Banco de la Nación Argentina -sucursal
tribunales- a la orden del juzgado y como pertenecientes a estas
ctuaciones. A sus efectos, líbrese oficio dejándose constancia
le los autorizados a correr con el diligenciamiento.- ...Con
especto al confronte, hágase saber al peticionante que deberá
enviar un mail a la casilla de correo institucional de este
Juzgado (incivil6(Qpin.gov.ar), indicando en el asunto número
le expediente v carátula, adjuntando el archivo en formato
WORD. Una vez firmado el mismo se procederá a digitalizar
por sistema LEX-100 a los fines de que pueda retirarlo en la
nesa de entradas del Juzgado.-” Fdo: ANDREA IMATZ jueza -
Quedan autorizados para correr con el
diligenciamiento del presente oficio los Dres. Orlando Rubén
Castaño, Ricardo Fabián D'Orazio, Ennio German La Valle, la Dra.
María Soledad Beati, el Sr. Santiago Ariel Casabal y las Sras.
Viviana Rampellini, Martina Lucia Corrado, Chiara Vittoria Di
Cicco Pompilio y Ludmila Rocio Carbonetti, indistintame

====================================================================================================
EJEMPLO CSV 3
====================================================================================================
|
TEXTO Y PATOS DE LA NOTIFICACIÓN LE!

Usuario a onectaldo: PEREZ Pamela Carolina - 27363991543 notificaciones.scba.gov.ar

Organismo: | JUZGADO DE FAMILIA N* 2 - SAN MIGUEL

Carátula: | PEREZ PAMELA CAROLINA C/ ROMERO HERNAN FACUNDO S/ COBRO DE
HONORARIOS ¿

Número de cauga: SG-3525-2024 mercado

Tipo de notificakión OFICIO ELECTRONICO => libre

Destinat rios: | 27363991543(Onotificaciones.scba.gov.ar

Fecha nlotificacibn: | 02/02/2026 02 ENE 2026

Alta o disponibilidad 30/12/2025 15:02:55

Firma digital: Firma válida EFE CION d

Firmado y Notifi adb por: GIRIBONE LOPEZ Maria Victoria. SECRETARIO -—- Certificado Correcto. Fecha de Firma:
30/12/2025 15:02:54

Firmado por: | GIRIBONE LOPEZ Maria Victoria. SECRETARIO —- Certificado Correcto. Fecha de Firma:
30/12/2025 15:02:53 PEREZ Pamela Carolina. --- Certificado Correcto. Fecha de Firma:
30/12/2025 12:27:30

OFICIO REITERATORIO JUDICIAL
| San Miguel, Diciembre del 2025.-

A pS) REJARIO A ARGO D

MERCADO LIBRE S.R.L.

OLICITADO|POR PARTE ACTORA.
dr MiTo

En mi eprácigr de Secretario del Juzgado de Familia N*”2 de San Miguel, Departamento Judicial San
Martín cal go| del Dr. Pablo ¡Ernesto Raffo Tengo el agrado de dirigirme a Ud. en autos
caratulados fPEREZ PAMELA CAROLINA C/ ROMERO HERNAN FACUNDO S/ COBRO DE
HONORARIOS", Expte. SG-3525-2024 en trámite por ante el Juzgado de Familia Nro. 2 con asiento

en San|Migukl a Departamento Judicial Gral. San Martin, sito en la calle Av. Ricardo Balbín 3100

San Miguel, pS cargo del Dr. RAFFO Pablo Ernesto. JUEZ, secretaria única, domicilio electrónico
juzfam2-smi(pjusbuenosaires.gov.ar, a los fines de reiterar que se trabe el embargo ordenado sobre

los fondos que posea el demandado en las cuentas a su nombre, Sr
ACUNDO, DNI N? 30.028.901. Dicho embargo deberá ser trabado hasta cubrir la suma de PESOS
CUATROCIENTOS CUARENTA Y SIETE MIL QUINIENTOS VEINTICUATRO ($447.524), integrada
por CUATROCIENTOS SEIS MIL OCHOCIENTOS CUARENTA PESOS ($406.840 honorarios
regulados) y[C 'ARENTA MIL SEISCIENTOS OCHENTA Y CUATRO PESOS ($40.684 aportes a|
cargo | del demandado) ; con más la suma de CIENTO OCHENTA MIL ($ 180.000), que se |
Dore estal| para responder a intereses y costas de la ejecución, LO QUE DA UN TOTAL, DE |
, RISCIENTO N IV QUINIENTO N ATRO P e,

O DL 4 A
: ñ
PROVEO DATOS D NTA DE AUTOS DONDE DEBERA DEPOSITAR L_MONTO

EMBARGADO: | N ” de Cuenta es 5055- 027-0525841/6 (Prop.: 752370) CBU
0140029827$05552584165. .
"El auta que ispone el libramiento del presente en su parte pertinente dice: “San Miguel, 10 de Junio |
de 2025”. “(l..) el importe de la suma reclamada de PESOS CUATROCIENTOS CUARENTA Y
SIETE | MIL QUINIENTOS VEINTICUATRO (447.524 $- comprensiva de 406.840 $ honorarios
regulados y 40.684 $ aportes) , con más la de PESOS. CIENTO OCHENTA MIL ($ 180.000 ), que se
estalh para responder a intereses y costas de la ejecución, trábese embargo sobre la cuenta
rcadd Pago a nombre del demandado, Sr. ROMERO HERNÁN FACUNDO, DNI N*
30.028,901, la cuyo fin ofície

====================================================================================================
EJEMPLO CSV 4
====================================================================================================
Error al descargar el archivo desde el bucket.

====================================================================================================
EJEMPLO CSV 5
====================================================================================================
12/12/25, 4:27| pim.

|
TEXTO Y DATOS DE LA NOTIFICACIÓN - SUPREMA CORTE DE JUSTICIA - NOTIFICACIONES ELECTRÓNICAS

TEXTO Y PATOS DE LA NOTIFICACIÓN
Usuario conectado: AMPUGNANI Cristian Gabriel - 20280616185Qnotificaciones.scba.gov.ar ral
Organismo: JUZGADO EN LO CIVIL Y COMERCIAL N*14 - LOMAS DE ZAMORA
Carátula CAMPOS CARLOS EDUARDO C/ ACEVEDO JULIO CESAR Y OTRO/A S/ DAÑOS Y

PERJ.AUTOM. C/LES. O MUERTE (EXC.ESTADO)

Número de cauga: 104002 ES mercado
Tipo de tifical ión OFICIO ELECTRONICO : o
Destinatarios: 20280616185Onotificaciones.scba.gov.a E
Fecha notificac|Hn: 18/11/2025 Ea > Y 0 2 E HE 2026
Alta/o disponibilidad 18/11/2025 08:25:37 p
Firma digital: Firma válida RECEPCION
Firmado y Notifilcado por: MAC GARVA Laura Florencia. AUXILIAR LETRADO --- Certificado Correcto. Fecha de

Firmado por:

Firma: 18/11/2025 08:25:33
AMPUGNANI Cristian Gabriel. --- Certificado Correcto. Fecha de Firma: 10/11/2025
16:04:14

Al Sr.
Merca
SRL 3
S]
Tengo
autos

[e]

tramit
Zamola, a cArg
Domingo Perón
REINA DO, ffitu
indiqu

El auto|que Qrd
2025. Atento
Argentiha Sf ES
Hágase sabgr a
será Buscripla
electrónico del
Digital.| Asin[sm
electrónico, Una
dicho aficio En

verificar la calid
verificación (que:

Se encuentra a
DNI N%40.0Q/.0
La respuegla

lzQj

[9
AUTOM. C/LES. O MUERTE (

n
ña del DNI N* 92.883.503 resulta ser usuario
el o lfs domicilios que registra

e
l manifestado.

|
quedando a disposición del interesado a los fines de

CATTANEO [JUEZ

OFICIO JUDICIAL

San Justo, de noviembre del 2025.-

ervicios de Procesamiento

9-8

D

de dirigirme a Usted en carácter de letrado apoderado de la parte actora en los
"CAMPOS CARLOS EDUARDO C/ ACEVEDO JULIO CESAR Y OTRO/A S/
EXC.ESTADO)" N* de Expediente:104002, que
Juzgado en lo Civil y Comercial N* 14 del Departamento Judicial de Lomas de
del Dr. Mariano Cattáneo, Secretaría única, con sede en Camino Pres. Juan
tersección Larroque, a fin de que: a fin de que informe: si el Sr. GONZÁLEZ
del servicio, y en caso afirmativo,
para la entrega de productos de compra.

a el presente, en su parte pertinente dice: "Lomas de Zamora, 13 de octubre del
líbrense los oficios a Mercado Libre SRL, DeRemate.com de
irst Label SRL, Tech Pack SRL y Mercado Pago Servicios a los fines solicitados.
peticionante que deberá enviar la pieza procesal en forma electrónica, la cual
igitalmente por el funcionario titular, la misma deberá contener el domicilio
estinatario para su posterior diligenciamiento a través del Sistema de Firma
, hágase saber que en caso de no contar la entidad oficiada con domicilio
vez firmada electrónicamente la pieza procesal por el funcionario, se visualizará
lista de sus notificaciones en el mismo Portal de Presentaciones electrónicas,
su impresión y diligenciamiento, pudiendo
del código QR o el ingreso del código de
de la notificación recibida. MARIANO M.

d de las firmas a través del escaneo
se generan luego de la impresión

torizado para diligenciar el presente en forma indistinta a Duva Agustina titular del

# 12. Detectar si hay HTML

In [27]:
def parece_html(texto):
    if pd.isna(texto):
        return False

    texto = str(texto).lower()

    patrones_html = [
        "<html", "<body", "<p", "<div", "<br", "<span", "<table",
        "<tr", "<td", "<strong", "<b", "&nbsp;", "&amp;", "</"
    ]

    return any(patron in texto for patron in patrones_html)

Aplicamos sobre la columna candidata:

In [28]:
df_csv["tiene_html_detectado"] = df_csv[COLUMNA_TEXTO_CSV].apply(parece_html)

df_csv["tiene_html_detectado"].value_counts()

tiene_html_detectado
False    2958
True       28
Name: count, dtype: int64

Y en porcentaje:

In [29]:
porcentaje_html_csv = df_csv["tiene_html_detectado"].mean() * 100

print(f"Porcentaje de registros con posible HTML: {porcentaje_html_csv:.2f}%")

Porcentaje de registros con posible HTML: 0.94%

# 13. Ver ejemplos que tienen HTML

In [30]:
ejemplos_html_csv = df_csv[df_csv["tiene_html_detectado"] == True][COLUMNA_TEXTO_CSV].dropna().astype(str).head(3)

for i, texto in enumerate(ejemplos_html_csv, start=1):
    print("=" * 100)
    print(f"EJEMPLO CON HTML {i}")
    print("=" * 100)
    print(texto[:3000])
    print()

====================================================================================================
EJEMPLO CON HTML 1
====================================================================================================
la lLoy NO 2 AROSA lo

REMITENTE 772201

/ICIOS DE PROCESAMIENTO SAL ARMANY CAROLINA PERDOMO ORTIZ
Apellido y nombre .

hb razón social q

ISA y E 96.176.316
Rama o al pal ÓN Ne
BISO 2 (1264) Ñ AV. CORRIENTES 2335, OF. 1* “A” Fecha
Código Postal Donnicilio real (1046)
Ñ C.A.B.A. C.A.B.A. Codigo Postai
Provincia Localidad TABA.

Provincia

lidano, remítole copia del requerimiento efecmado 2 CONTACTO GARANTIDO S.A, rigicodo a Ud. las mismas intimaciones y «perdbimientos:
to CD 35094083 O, de fecha 13/12/2025, por resultar sus términos fsos, maliciosos e improcedentes. Ratifico en todos sus términos mis anteriores
que reiteradamente vengo reclamando y que Ud. persiste en 1acumplix, y la cotalidad de los reclamos, jotimaciones y apercibimienzos efecnlados en

estras manifestaciones. Niego y rechazo una vez más encontrarme po reserva de puesto como Ud, refiere, en relación a lo cual le reitero —evamente
Ceabajo a disposición, la reserva de puesto ha cesado cuando mi médico tratante «Dr. José A. Pormay me ha indicado rai alla médica por l- patología
2 disposición para reintegrarme 2 la prestación de mis (2225), con uns serie de indicaciones a efectos de ana mejor reinserción y readaptación 2 2mis
en el certificado médico de fecha 30/10/2025 expedido por el arado profesional; habiéadome asinismo indicado dicho profesional -cras haberle la
as que Ud. me ha indicado realizar- la recomendación de que en casa de reinregrarme a mi actividad laboral lo hiciera deseripeñando Imis tareas en

da de precaución a Én de un mejor reiaserción panlsina a la prestación de mis tareas, ya efectos de mantener mi estabilidad emocional, favorecer
resgravamiento de la patología psiquiátrica sufada tras la licencis que he estado cussaado. a
q irmad del alta médica otorgada por el Dr. Pormoy, y de las indicacones que se me han efectuado, vengo inimando a vuestra parte insistentemente a fa

sas adordes a la totalidad de las presempeiones médicas y cumpla su deber de ocupación (art 78 LOT); lo cual Ud. persiste en incumplir.

Ahión n vuestro persistente incumplimiento 2 las inimaciones oportunamente cursadas no obstante el transcurso del plazo legal y no obstante mis insistentes

en la injustificada neganva de tareas de vuestra parte y falo de cumplimiento de su deber” de ocupación
dad con las indicaciones que mi médico tratante el Dr. José A. Pormoy me ha
ián y serdapración laboral 1ras la hcencia laboral cursada, tal como consta en el ceruficado médico que le fuera opormna y fehacientemente notificado,
electrónico; y habiendo Ud. peesistdo ea incumplir con la dación de mis tare2s conforme dichas indicaciones, pretendiendo mantenerme injustunente
:1o en forma indefinida), la falta de pago de los haberes devengados, adeudados y reclamados (los cuales ld. se me han abonado en forma insuídente
srábbia, efecruando descuentos improcedentes, y los cuales posteriormente se ha negado a Ud. a abonazme no obstante haberse encontrado mi fuerza de trabajo 2
ad con lo indicado por mi médico

====================================================================================================
EJEMPLO CON HTML 2
====================================================================================================
AR
EL!
LA

DESTINA
DO
CABA

pol el la
Consum

TOLERA

con los i
bajo ape

sustento
y art. 461

MAR DEL PLATA, 07 de Enero del 2026

Cosa,
-2

|D: AV. CASEROS 3039 PISO 2 A

| 008009

C.R.: 126

E Cu
ARIO: MERCADOLIBRE S.R.L UN

Me dirijo a Ud con motivo de la ACTUACIÓN ADMINISTRATIVA N* 79,304/2026 efectuado
Sr/a. FRANCHETTO GISELLA ALEJANDRA ante ésta Dirección General de Protección al
Hor de la Municipalidad de General Pueyrredon sita en calle BELGRANO 3467 de esta ciudad a los

finés de OTIFICARLE_ que deberá concurrir de manera obligatoria a la Audiencia Conciliatoria_a
celebrarsg

elldía 28 DE ENERO DEL 2026 A LAS 12:15 HS (CONTANDO CON 15 MINUTOS DE
CIA) bajo apercibimiento de lo dispuesto por el Art. 48 de la Ley 13.133.

En el acto de la audiencia, el compareciente deberá acreditar la personería que invocare
strumentos idóneos a tal fin, debiendo además constituir domicilio dentro del radio del Munitipio
ibimiento de lo dispuesto por el Art. 51 de la Ley 13.133.

A sus efectos se acompaña a la presente copia del reclamo. Lo dispuesto encuentra
bn el art.1%, art.45%, 2? párrafo art.44* y conc. de la Ley Nacional 24240 de Defensa del Consumidor
y 47" de la Ley 13133.

ARTICULD 46; Recepcionada la denuncia, se abrirá la instancia conciliatoria, a cuyos fines se designará audiencia. La

nofificació!

de la misma se hará por escrito. -

ARTICULO 47; Con la comparecencia de las partes se celebrará audiencia de conciliación, labrándose acta. El acuerdo
setá rubritado| por los intervinientes y homologado. El acuerdo homologado suspenderá el procedimiento en cualquier

momento
audiencia
relación $
descarga
sahción a

ARTICU
hamologá
establecipl
acordada

NOTA: fÑ
-salvo|l

sanción

En Mbr del Plata, a los ...... días del mes de ...
Siendo atendido por

Hel sumario hasta la oportunidad del cierre de la instancia conciliatoria. Si no hubiere acuerdo, o notifica da la
lel denunciado no compareciere sin causa justificada, se formulará auto de imputación el que contendrá una
cinta de los hechos y la determinación de la norma legal infringida. Notificado el mismo y efectuado el
bertinente, en este estado se elevarán las actuaciones al funcionario Municipal competente quien resolverá la

plicable. Ello, sin perjuicio de las facultades conferidas por el artículo 44? de la Ley 24.240.-

D 48: La incomparecencia injustificada a la audiencia de conciliación y/o el incumplimiento de los acuerdos
os, se considera violación de la Ley 24.240 y de esta Ley. El infractor será pasible de las sanciones
fas en la presente, sin perjuicio del cumplimiento imperativo de las obligaciones que las partes hubieran

Se hace saber que la presentación de-escritos no suspenderá la audiencia fijada
esolución expresa en tal sentido- siendo pasible en caso de incomparecencia de la
establecida en el Art. 48 de la Ley 13.133.

Se adjunta copia del reclamo y la documentación respaldatoria.

+ Cutropia Ana
QUEDA UD. DEBIDAMENTE NOTIFICADO

horas compatecí en el domicilio indicado y
en

====================================================================================================
EJEMPLO CON HTML 3
====================================================================================================
] y ==

CEDULA DE NOTIFICACIÓN

mares 1 12 de ENERO de 2026.

libre

RE -EPCION.

e dirijo a usted con relación al reclamo que tramita bajo ta Denuncia 79238/2025 efectuado por la
'ANSOLA CLAUDIO ante esta Dirección General de Protección al Consumidor, sito en calle
3RANO 3467 de esta ciudad, a los fines de NOTIFICARLE que se ha fijada Audiencia Conc:liatoria a
| celeb EL DÍA 20 DE ENERO DE 2026 ALAS 08:15 HS., la que se celebrará de manera presencial. La
lasistéhcia es de carácter obligatorio, bajo apercibimiento de aplicar lo dispuesta por el Art. 48 de le Ley
B. Lo dispuesto halla su sustento en el art.1%, art.45%, 2” párrafo art.44” y conc. de la Ley Nacional
] de Defensa del Consumidor y art. 48%, 47" y 48 de la LEY 13133.

dl acto de la audiencia, el compareciente deberá acreditar la personería que invocare con los
entos idóneos a tal fin, debiendo además constituir domicilio dentro del radio del Municipio bajo
élbimiento de lo dispuesta por el Art. 51 de la Ley 13.133.

ULO 46: Recepcionada la denuncia, se abrirá la instancia conciliatoria, a cuyos fines se
ará audiencia. La notificación de la misma se hará por escrito.

ULO 47: Con la comparecencia de las partes se celebrará audiencia de contiliación, labrándose
El lacuerdo será rubricado por los intervinientes y homologado. El acuerdo homologado
Enderá el procedimiento en cualquier momento del sumario hasta la oportunidad del cierre de la
cia conciliatoria. Si no hubiere acuerdo, o notificada la audiencia el denunciado no compareciere
usa justificada, se formulará auto de imputación el que contendrá una relación sucinta de los
s y la determinación de la norma legal infringida. Notificado el mismo y efectuado el descargo
nte, en este estado se elevarán las actuaciones al funcionario Municipal competente quien

[4]

erá la sanción aplicable. Ello, sin perjuicio de las facultades conferidas por el artículo 44? de la

ULO 48: La incomparecencia injustificada a la audiencia de conciliación y/o el incumplimientr:
E acuerdos homologados, se considera violación de la Ley 24.240 y de esta Ley. El infractor será

aciones que las partes hubieran acordado
nto: COPIA DE DENUNCIA.

QUEDA UD. DEBIDAMENT
FIRMA:


2.-

Siendo atendido PO cccccncciconniconninnocinncinaano romeros con documento NO accion quien manifestó ser
q armes.» Y previa lectura, procedí a notificarlo,
a) HACIENDOLE ENTREGA de una Cédula de Notificación de un mismo tenor, con las copias respectivas, e invitándolo a firmar
b)  HACIENDOLE ENTREGA de una Cédula de Notificación de un mismo tenor, con las copias respectivas, e invitándolo a firmar,
se deja constancia que SE NIEGA A FIRMAR
NO ENCONTRANDOSE PERSONA ALGUNA QUE QUIERA RECIBIRLA

[Mal cacncconronninnnnnconcoranornooo roo conorrarr noc anao coi oocnoni enorcacconn car cacicc) O PUEDA RECIBIRLA / LOCAL CERRADO - SE
FIJA EN PUERTA (CONF, ORD. GRAL 267 — ART.65)

Firma Notificado Firma Notificador

MAR

CEDULA DE NOTIFICACIÓN

Mar del Plata, 18 de diciembre de 2025.

NATARIO: MERCA

# Mejor verificación del HTML

Función para saber qué patrón activó el True:

In [31]:
def detectar_patrones_html(texto):
    if pd.isna(texto):
        return []

    texto = str(texto).lower()

    patrones_html = [
        "<html", "<body", "<p", "<div", "<br", "<span", "<table",
        "<tr", "<td", "<strong", "<b", "&nbsp;", "&amp;", "</"
    ]

    encontrados = []

    for patron in patrones_html:
        if patron in texto:
            encontrados.append(patron)

    return encontrados

Ejecutar:

In [32]:
df_csv["patrones_html_detectados"] = df_csv[COLUMNA_TEXTO_CSV].apply(detectar_patrones_html)

df_csv[df_csv["tiene_html_detectado"] == True][
    ["id", "nombre", "clasificacion", "patrones_html_detectados"]
].head(28)

,id,nombre,clasificacion,patrones_html_detectados
175,496886,Intimacion,Juicio,[<p]
335,498324,Audiencia,Oficio,[<p]
403,499481,Audiencia,Oficio,[<p]
425,500696,Reclamo,Defensa Consumidor,[<b]
428,500699,Audiencia,Oficio,[<tr]
513,502596,Reclamo,Defensa Consumidor,[<p]
514,502597,Carta Simple,Defensa Consumidor,[<b]
582,502668,Intimacion,Juicio,[<p]
611,503769,Audiencia,Oficio,"[<p, <br, <b]"
960,510943,Audiencia,Oficio,[<p]
1161,514525,Demanda,Juicio,[</]
1212,515722,Audiencia,Oficio,[<b]
1427,518825,Intimacion,Juicio,[<b]
1917,529791,Reclamo,Defensa Consumidor,[<p]
1937,529827,Embargo - usuario,Embargo,[<p]
2007,532427,Demanda,Juicio,[</]
2008,532428,Audiencia,Oficio,[<b]
2011,532433,Carta Simple,Defensa Consumidor,[<b]
2333,538026,Audiencia,Oficio,"[<p, <b]"
2334,538027,Reclamo,Defensa Consumidor,[<p]
2355,538059,Embargo - usuario,Embargo,[<p]
2509,538215,Mediacion,Mediación,[<p]
2536,538242,Demanda,Juicio,[<p]
2659,542999,Demanda,Juicio,[</]
2711,543547,Audiencia,Oficio,[<p]
2726,543569,Notificacion procesal,Juicio,[<p]
2867,546255,Reclamo,Defensa Consumidor,[<b]
2972,547386,Demanda,Juicio,[<b]

# Ver ejemplos más claros de esos casos

In [33]:
casos_html = df_csv[df_csv["tiene_html_detectado"] == True]

for i, row in casos_html.head(5).iterrows():
    print("=" * 100)
    print("ID:", row["id"])
    print("NOMBRE:", row["nombre"])
    print("CLASIFICACION:", row["clasificacion"])
    print("PATRONES:", row["patrones_html_detectados"])
    print("=" * 100)
    print(str(row[COLUMNA_TEXTO_CSV])[:3000])
    print()

====================================================================================================
ID: 496886
NOMBRE: Intimacion
CLASIFICACION: Juicio
PATRONES: ['<p']
====================================================================================================
la lLoy NO 2 AROSA lo

REMITENTE 772201

/ICIOS DE PROCESAMIENTO SAL ARMANY CAROLINA PERDOMO ORTIZ
Apellido y nombre .

hb razón social q

ISA y E 96.176.316
Rama o al pal ÓN Ne
BISO 2 (1264) Ñ AV. CORRIENTES 2335, OF. 1* “A” Fecha
Código Postal Donnicilio real (1046)
Ñ C.A.B.A. C.A.B.A. Codigo Postai
Provincia Localidad TABA.

Provincia

lidano, remítole copia del requerimiento efecmado 2 CONTACTO GARANTIDO S.A, rigicodo a Ud. las mismas intimaciones y «perdbimientos:
to CD 35094083 O, de fecha 13/12/2025, por resultar sus términos fsos, maliciosos e improcedentes. Ratifico en todos sus términos mis anteriores
que reiteradamente vengo reclamando y que Ud. persiste en 1acumplix, y la cotalidad de los reclamos, jotimaciones y apercibimienzos efecnlados en

estras manifestaciones. Niego y rechazo una vez más encontrarme po reserva de puesto como Ud, refiere, en relación a lo cual le reitero —evamente
Ceabajo a disposición, la reserva de puesto ha cesado cuando mi médico tratante «Dr. José A. Pormay me ha indicado rai alla médica por l- patología
2 disposición para reintegrarme 2 la prestación de mis (2225), con uns serie de indicaciones a efectos de ana mejor reinserción y readaptación 2 2mis
en el certificado médico de fecha 30/10/2025 expedido por el arado profesional; habiéadome asinismo indicado dicho profesional -cras haberle la
as que Ud. me ha indicado realizar- la recomendación de que en casa de reinregrarme a mi actividad laboral lo hiciera deseripeñando Imis tareas en

da de precaución a Én de un mejor reiaserción panlsina a la prestación de mis tareas, ya efectos de mantener mi estabilidad emocional, favorecer
resgravamiento de la patología psiquiátrica sufada tras la licencis que he estado cussaado. a
q irmad del alta médica otorgada por el Dr. Pormoy, y de las indicacones que se me han efectuado, vengo inimando a vuestra parte insistentemente a fa

sas adordes a la totalidad de las presempeiones médicas y cumpla su deber de ocupación (art 78 LOT); lo cual Ud. persiste en incumplir.

Ahión n vuestro persistente incumplimiento 2 las inimaciones oportunamente cursadas no obstante el transcurso del plazo legal y no obstante mis insistentes

en la injustificada neganva de tareas de vuestra parte y falo de cumplimiento de su deber” de ocupación
dad con las indicaciones que mi médico tratante el Dr. José A. Pormoy me ha
ián y serdapración laboral 1ras la hcencia laboral cursada, tal como consta en el ceruficado médico que le fuera opormna y fehacientemente notificado,
electrónico; y habiendo Ud. peesistdo ea incumplir con la dación de mis tare2s conforme dichas indicaciones, pretendiendo mantenerme injustunente
:1o en forma indefinida), la falta de pago de los haberes devengados, adeudados y reclamados (los cuales ld. se me han abonado en forma insuídente
srábbia, efecruando descuentos improcedentes, y los cuales posteriormente se ha negado a Ud. a abonazme no obstante haberse encontrado mi fuerza de trabajo 2
ad con lo indicado por mi médico

====================================================================================================
ID: 498324
NOMBRE: Audiencia
CLASIFICACION: Oficio
PATRONES: ['<p']
====================================================================================================
AR
EL!
LA

DESTINA
DO
CABA

pol el la
Consum

TOLERA

con los i
bajo ape

sustento
y art. 461

MAR DEL PLATA, 07 de Enero del 2026

Cosa,
-2

|D: AV. CASEROS 3039 PISO 2 A

| 008009

C.R.: 126

E Cu
ARIO: MERCADOLIBRE S.R.L UN

Me dirijo a Ud con motivo de la ACTUACIÓN ADMINISTRATIVA N* 79,304/2026 efectuado
Sr/a. FRANCHETTO GISELLA ALEJANDRA ante ésta Dirección General de Protección al
Hor de la Municipalidad de General Pueyrredon sita en calle BELGRANO 3467 de esta ciudad a los

finés de OTIFICARLE_ que deberá concurrir de manera obligatoria a la Audiencia Conciliatoria_a
celebrarsg

elldía 28 DE ENERO DEL 2026 A LAS 12:15 HS (CONTANDO CON 15 MINUTOS DE
CIA) bajo apercibimiento de lo dispuesto por el Art. 48 de la Ley 13.133.

En el acto de la audiencia, el compareciente deberá acreditar la personería que invocare
strumentos idóneos a tal fin, debiendo además constituir domicilio dentro del radio del Munitipio
ibimiento de lo dispuesto por el Art. 51 de la Ley 13.133.

A sus efectos se acompaña a la presente copia del reclamo. Lo dispuesto encuentra
bn el art.1%, art.45%, 2? párrafo art.44* y conc. de la Ley Nacional 24240 de Defensa del Consumidor
y 47" de la Ley 13133.

ARTICULD 46; Recepcionada la denuncia, se abrirá la instancia conciliatoria, a cuyos fines se designará audiencia. La

nofificació!

de la misma se hará por escrito. -

ARTICULO 47; Con la comparecencia de las partes se celebrará audiencia de conciliación, labrándose acta. El acuerdo
setá rubritado| por los intervinientes y homologado. El acuerdo homologado suspenderá el procedimiento en cualquier

momento
audiencia
relación $
descarga
sahción a

ARTICU
hamologá
establecipl
acordada

NOTA: fÑ
-salvo|l

sanción

En Mbr del Plata, a los ...... días del mes de ...
Siendo atendido por

Hel sumario hasta la oportunidad del cierre de la instancia conciliatoria. Si no hubiere acuerdo, o notifica da la
lel denunciado no compareciere sin causa justificada, se formulará auto de imputación el que contendrá una
cinta de los hechos y la determinación de la norma legal infringida. Notificado el mismo y efectuado el
bertinente, en este estado se elevarán las actuaciones al funcionario Municipal competente quien resolverá la

plicable. Ello, sin perjuicio de las facultades conferidas por el artículo 44? de la Ley 24.240.-

D 48: La incomparecencia injustificada a la audiencia de conciliación y/o el incumplimiento de los acuerdos
os, se considera violación de la Ley 24.240 y de esta Ley. El infractor será pasible de las sanciones
fas en la presente, sin perjuicio del cumplimiento imperativo de las obligaciones que las partes hubieran

Se hace saber que la presentación de-escritos no suspenderá la audiencia fijada
esolución expresa en tal sentido- siendo pasible en caso de incomparecencia de la
establecida en el Art. 48 de la Ley 13.133.

Se adjunta copia del reclamo y la documentación respaldatoria.

+ Cutropia Ana
QUEDA UD. DEBIDAMENTE NOTIFICADO

horas compatecí en el domicilio indicado y
en

====================================================================================================
ID: 499481
NOMBRE: Audiencia
CLASIFICACION: Oficio
PATRONES: ['<p']
====================================================================================================
] y ==

CEDULA DE NOTIFICACIÓN

mares 1 12 de ENERO de 2026.

libre

RE -EPCION.

e dirijo a usted con relación al reclamo que tramita bajo ta Denuncia 79238/2025 efectuado por la
'ANSOLA CLAUDIO ante esta Dirección General de Protección al Consumidor, sito en calle
3RANO 3467 de esta ciudad, a los fines de NOTIFICARLE que se ha fijada Audiencia Conc:liatoria a
| celeb EL DÍA 20 DE ENERO DE 2026 ALAS 08:15 HS., la que se celebrará de manera presencial. La
lasistéhcia es de carácter obligatorio, bajo apercibimiento de aplicar lo dispuesta por el Art. 48 de le Ley
B. Lo dispuesto halla su sustento en el art.1%, art.45%, 2” párrafo art.44” y conc. de la Ley Nacional
] de Defensa del Consumidor y art. 48%, 47" y 48 de la LEY 13133.

dl acto de la audiencia, el compareciente deberá acreditar la personería que invocare con los
entos idóneos a tal fin, debiendo además constituir domicilio dentro del radio del Municipio bajo
élbimiento de lo dispuesta por el Art. 51 de la Ley 13.133.

ULO 46: Recepcionada la denuncia, se abrirá la instancia conciliatoria, a cuyos fines se
ará audiencia. La notificación de la misma se hará por escrito.

ULO 47: Con la comparecencia de las partes se celebrará audiencia de contiliación, labrándose
El lacuerdo será rubricado por los intervinientes y homologado. El acuerdo homologado
Enderá el procedimiento en cualquier momento del sumario hasta la oportunidad del cierre de la
cia conciliatoria. Si no hubiere acuerdo, o notificada la audiencia el denunciado no compareciere
usa justificada, se formulará auto de imputación el que contendrá una relación sucinta de los
s y la determinación de la norma legal infringida. Notificado el mismo y efectuado el descargo
nte, en este estado se elevarán las actuaciones al funcionario Municipal competente quien

[4]

erá la sanción aplicable. Ello, sin perjuicio de las facultades conferidas por el artículo 44? de la

ULO 48: La incomparecencia injustificada a la audiencia de conciliación y/o el incumplimientr:
E acuerdos homologados, se considera violación de la Ley 24.240 y de esta Ley. El infractor será

aciones que las partes hubieran acordado
nto: COPIA DE DENUNCIA.

QUEDA UD. DEBIDAMENT
FIRMA:


2.-

Siendo atendido PO cccccncciconniconninnocinncinaano romeros con documento NO accion quien manifestó ser
q armes.» Y previa lectura, procedí a notificarlo,
a) HACIENDOLE ENTREGA de una Cédula de Notificación de un mismo tenor, con las copias respectivas, e invitándolo a firmar
b)  HACIENDOLE ENTREGA de una Cédula de Notificación de un mismo tenor, con las copias respectivas, e invitándolo a firmar,
se deja constancia que SE NIEGA A FIRMAR
NO ENCONTRANDOSE PERSONA ALGUNA QUE QUIERA RECIBIRLA

[Mal cacncconronninnnnnconcoranornooo roo conorrarr noc anao coi oocnoni enorcacconn car cacicc) O PUEDA RECIBIRLA / LOCAL CERRADO - SE
FIJA EN PUERTA (CONF, ORD. GRAL 267 — ART.65)

Firma Notificado Firma Notificador

MAR

CEDULA DE NOTIFICACIÓN

Mar del Plata, 18 de diciembre de 2025.

NATARIO: MERCA

====================================================================================================
ID: 500696
NOMBRE: Reclamo
CLASIFICACION: Defensa Consumidor
PATRONES: ['<b']
====================================================================================================
Top. 14)

.
IMNECCIÓN AEREPAL DE.

Clio dea road eng cr COMERCIO

Mo Sl
í Ministerio di
| ES) ECONOMÍA ESS

FORMULARIO DE TRÁMITE DE DENUNCIA
DEFENSA DEL CONSUMIDOR |

DEFENSA DEL CONS

Santiago del Estero,

Consumidor, con base en los Desachos que me asisten por la Ley NO 24.240 y Sa

lahnentadipnes y el Código Civil y Comercial y la Ley Provincial N* 7148, me dirijo a la Direcció!

aral de Fomercio — Departamento de Defensa del Consumidor, a efectos de formular el siguiente
o:

sl Re |

[PAFOS DEl DENUNCIANTE |

“sa (caied 125 — 3 ome Cami $ ara,
| Papita 0 Código Postal: 41200
Teléfono:

as AA 5059 E
OBSERVA! ONE S (presenta poder, al

ctúa a través de un representante letrado, etc.):

LAS EMPRESAS DENUNCIADAS
Social: _1 z » PALA A
E Vio p246! A

Es a

Código Postal: M230c0c

o bre a

Domicilio:

Lotalidad: |! Código Postal:

BREV D ESCRIPCIÓN DEL MOTIVO DE su DENUNCIA:

e. y > = = e

A a

AQ Ne cal [a
MM L 7 '

MAA! pr

dinordo

JO

a

|

AAA 000 2 E 107

EH: Ministerio de. Y,
3 ECONOMÍA DSC

SY coser dela trvioco se ratazo tato COMERCIO

arque con una “X” según corresponda:

1 q
A Problemas con el servicio |

[Publicidad Engañosa

Producto Defectuoso Problemas con la Garantía

Problemas con la Facturación r Falta de Documentación

e

Intereses Abusivos incumplimiento de Contrato

Trato Indigno Deber de Información

Otro: Ñ A

OBJETO DEL RECLAMO:
¿COMO ESPERA QUE SE RESUELVA?

Marque con una “X” según corresponda:

Cambio de producto 3] Bonificación en el abono ós |
Reparación del producto / servicio técnico Xx Anulación del contrato E
1
Ñ Devolución dal dinero | Otro ]

Especifique:

PRUEBA OFRECIDA Y DOCUMENTAL ACOMPAÑADA:

1.-Que tenga por interpuesta formal denuncia, por violación a ta ley 24.240 sus modificatorias y complernentarias.-

2.-Que se me tenga por presentado en el carácter invocado, de Usuario y Consumidor.-

3.-Se promueva la instancia conciliatoria, en pos de la solución a m: raclamo acorde lo dispone Art. 25 Ley N'7.14£ que refrenda al Decreto
Reglamentario 0573/14,-

4.-Que en el caso que se encuentren configuradas violaciones a tos preceptos de la Ley de Detensa al Usuario y Cersumidor, sa apliquen las
sanciones del Art 18 del Decreto Reglamentario 0373/14 refrencado por la da Ley provincial 7.148,ccn sus agravantes, basados en el carácter de
reincidente, la cuantía de los beneficios indebidarnente ubtenidos, su proyección económica ei pañigro potencial de su yenaraiización para todos
los usuarios, y la repercusión de estas infracciones atento la posición de la Firma en el mercado.-

5.-Que se haga lugar a la prueba documenta! presentada, y que se ordene en virtud del principio de diriamismo da ta prueba, que tas Firmas
denunciadas, apcrten al proceso aquella documental conducente, al esclarecimiento de la verdad objativa (Art. 53 Lay 24.240).-

6.-Que atento las resiriccicnes establecidas por la Ley Nacional 26.993 Art. 58, y no siendo posible reclamos correspondientes al Daño Directo

iva. hago expresa reserva

(daño em

====================================================================================================
ID: 500699
NOMBRE: Audiencia
CLASIFICACION: Oficio
PATRONES: ['<tr']
====================================================================================================
NOM

DOM (

Tres Los//as

MUNICIPIO
Tres Lomas- Buenos Aires — Argentina |
mercado
FICI FENSA DEL CONSUMIDOR ES ¡ore
vet al ¡AD DE TRES LOMAS £ Woo : o
vadavia| 14
== UA "19 ENE 2026
O coria MN WI, a
cprreo eléx : defensaconsumidortreslomasfWgmail.com pel "ly y

ceoua Denon. RECEPCION

Tres Lomas, 9 de Enero de 2026-

DEL DENUNCIADO: MERCADO PAGO

ILIO: Ayenida Caseros 3039 Piso 2 C.A.B.A

irijo a usted a fin de comunicarle que en el marco del expediente nro. 4126-1587/2026
STIAN C/ MERCADO PAGO S/ PROCEDIMIENTO ADMINISTRATIVO 24240 que
esta Oficina Municipal de Defensa del Consumidor, sita en calle Rivadavia 149 de Tres Lomas,
icurrir con motivo de ta denuncia efectuada por CRISTIAN MARTIN a la audiencia de
ijada para el día 9 de FEBRERO de 2026 a las 11:00hs.. A continuación se transcribe lo
los artículos 48 primer párrafo y 51 primer párrafo de la Ley 13.133,

lo 48: La incomparecencia injustificada a la audiencia de conciliación y/o el incumplimiento
homologados, se considera violación de la Ley 24.240 y de esta Ley.

rulo 514: En el escrito de descargo o en su primera presentación, el presunto infractor deberá

domicilio dentro del radio del Municipio y acreditar personería. Cuando no acredite personería se le
d|para que en el término de cinco (5) días hábiles subsane la omisión bajo apercibimiento de tenerto
wesentado.

vez se informa que no obstante estar fijada ta audiencia, se podrá comunicar con el consumidor

presente se acompaña copia de la denuncia y documentación adjunta.
'A'UD. DEBIDAMENTE NOTIFICADO

tE: una solución del conflicto.

nia

ía Virginia Solari cn

Mari aboada TE,
q v-F85-CATL Po L;


2680) 291T

OIGIDIMUM

aniinagrA —2e0A 2009UR omo] 2017

” í
31H SOCIMUZAOO 130 ALUITIO 30 AMIDITO
TAMOS 2947 33 CAGADA
LEO A PL DA
OS 347 er. AOS 7
. ZOTDE»-IMSOE? POLLO 437
nro hemoPranoortrobimoncosaiad onda DO
a]
10133 á
Ed 3 1123H *ODIATITTOM 30 AJYOZDO

«AOS 90 man?tab 2 2amo) aenT

OD DOOR WAR ARO ASILO,
LADO Con VEDA rr 0 bir OLI OO

ALOS1VIAL-IL LA ¿om aénsibaaxs lab conem ls na sup ahedinumoo 3h ni a bajes 5 o(hib 2M
oun DASBS OVITARTRIMIMOA OTUZIMIORION 12 ODAI ODADAIM 1) MATTEIAO VTTAAM
26m) 207 ab Oe svebeyiA liso 1 sh sobirmuanoS tab 600190 sb legoinuM sobRO stes sins ejimert
ab cioneibos sí 4 MITRAM MAIT2IAD 109 sbeutie sonunab al $5 ctom 50) mmunnoo nimedab
al adimenea! 92 nobsunitio) A .2100:15 zal e 3505 sb 0439837 9b € sb ls eq cbsiñ núbesilonos
CELE? yal als eng sm (2 y ote q remo 82 aotuolós 201 na ota unaib

Orea mor e da rhralo ono 3) Ant € e AENA TÍ ENANA 5) 32 Ol
RI Ma A A UA

colla bed can la o IO, Y A O Up ab giran de 1 LA aut
AE INGA ELLO DA OA) NOA EA Y CA o OE O nea, mola muaa
E O A MA AI
VPO, 04 0

s9bimanos la nos avoimumco fiboa e sonas e: sbsmM stes sinsiado on sup simoini se sav us £
obnoo tab nótbwlnz say 5 asdtms sh nf e

Sibe roortramoab y SOMNUNSD El 90 5003 SABQMO)S Se sinsetna el no)

OGADIINCA ATHIMAOIATO ,01! AQIUO

rato? edeiguiV shirM 010
'obirmaeno) Isb sensiad 00 isainimM srivO

!
ll

Ir

dar

# Revision de la columna clasificacion

Como ya vimos que existe clasificacion

In [34]:
df_csv["clasificacion"].value_counts(dropna=False)

clasificacion
Embargo               848
Defensa Consumidor    719
Juicio                597
Oficio                562
Mediación             222
SECLO                  38
Name: count, dtype: int64

# 14. Detectar documentos repetidos en CSV

Primero por fila completa:

In [39]:
duplicados_id_csv = df_csv.duplicated(subset=["id"]).sum()
duplicados_texto_csv = df_csv.duplicated(subset=[COLUMNA_TEXTO_CSV]).sum()
duplicados_documento_csv = df_csv.duplicated(
    subset=[COLUMNA_TEXTO_CSV, "nombre", "clasificacion"]
).sum()

print("IDs duplicados:", duplicados_id_csv)
print("Textos legales duplicados:", duplicados_texto_csv)
print("Documentos duplicados por texto + nombre + clasificación:", duplicados_documento_csv)

IDs duplicados: 0
Textos legales duplicados: 738
Documentos duplicados por texto + nombre + clasificación: 714

Después por texto legal, que es más útil:

In [40]:
duplicados_texto_csv = df_csv.duplicated(subset=[COLUMNA_TEXTO_CSV]).sum()

print("Textos legales duplicados:", duplicados_texto_csv)

Textos legales duplicados: 738

### Inspeccion de los duplicados

In [41]:
df_duplicados_texto = df_csv[
    df_csv.duplicated(subset=[COLUMNA_TEXTO_CSV], keep=False)
].sort_values(by=COLUMNA_TEXTO_CSV)

print("Cantidad de filas involucradas en textos duplicados:", df_duplicados_texto.shape[0])

df_duplicados_texto[["id", "nombre", "clasificacion", COLUMNA_TEXTO_CSV]].head(20)

Cantidad de filas involucradas en textos duplicados: 744

,id,nombre,clasificacion,texto_ocr
1860,527273,Embargo - usuario,Embargo,\n
879,508914,Notificacion procesal,Juicio,\n
880,508915,Embargo - usuario,Embargo,\n
882,508917,Embargo - usuario,Embargo,\n
2205,534544,Embargo - usuario,Embargo,\n
2134,532572,Intimacion,Juicio,Error al descargar el archivo desde el bucket.
2096,532534,Embargo - usuario,Embargo,Error al descargar el archivo desde el bucket.
2097,532535,Demanda,Juicio,Error al descargar el archivo desde el bucket.
2103,532541,SECLO,SECLO,Error al descargar el archivo desde el bucket.
2104,532542,SECLO,SECLO,Error al descargar el archivo desde el bucket.
2108,532546,Intimacion,Juicio,Error al descargar el archivo desde el bucket.
2118,532556,Intimacion,Juicio,Error al descargar el archivo desde el bucket.
2120,532558,Intimacion,Juicio,Error al descargar el archivo desde el bucket.
2123,532561,Intimacion,Juicio,Error al descargar el archivo desde el bucket.
2124,532562,Intimacion,Juicio,Error al descargar el archivo desde el bucket.
2125,532563,Intimacion,Juicio,Error al descargar el archivo desde el bucket.
2095,532533,Solicitud de informacion de usuarios,Oficio,Error al descargar el archivo desde el bucket.
2128,532566,Intimacion,Juicio,Error al descargar el archivo desde el bucket.
2140,532578,Intimacion,Juicio,Error al descargar el archivo desde el bucket.
2139,532577,Mediacion,Mediación,Error al descargar el archivo desde el bucket.

# 15. Detectar posibles columnas de tipo de documento

Vamos a buscar columnas que tengan pocos valores únicos, porque podrían ser tipo, categoría, clasificación, estado, etc.

In [49]:
def columnas_categoricas(df, max_unicos=30):
    resultados = []

    for col in df.columns:
        serie = df[col]

        # Si la columna contiene listas/dicts/sets, la salteamos
        tiene_valores_no_hashables = serie.dropna().apply(
            lambda x: isinstance(x, (list, dict, set))
        ).any()

        if tiene_valores_no_hashables:
            continue

        unicos = serie.nunique(dropna=True)

        if unicos <= max_unicos:
            resultados.append({
                "columna": col,
                "valores_unicos": int(unicos),
                "nulos": int(serie.isna().sum())
            })

    if len(resultados) == 0:
        return pd.DataFrame(columns=["columna", "valores_unicos", "nulos"])

    return pd.DataFrame(resultados).sort_values(by="valores_unicos")

In [50]:
categoricas_csv = columnas_categoricas(df_csv, max_unicos=30)

display(categoricas_csv)

                columna  valores_unicos  nulos
2  tiene_html_detectado               2      0
3      estado_texto_ocr               4      0
1         clasificacion               6      0
0                nombre              18      0

# Ahora detectemos textos inválidos o errores OCR
Esto es clave porque ya vimos:

\n
Error al descargar el archivo desde el bucket.

In [46]:
def detectar_problema_texto_ocr(texto):
    if pd.isna(texto):
        return "nulo"

    texto_str = str(texto).strip()

    if texto_str == "":
        return "vacio"

    if texto_str == "\\n" or texto_str == "\n":
        return "solo_salto_linea"

    if "Error al descargar el archivo desde el bucket" in texto_str:
        return "error_descarga_bucket"

    if len(texto_str) < 50:
        return "texto_muy_corto"

    return "ok"

In [47]:
df_csv["estado_texto_ocr"] = df_csv["texto_ocr"].apply(detectar_problema_texto_ocr)

df_csv["estado_texto_ocr"].value_counts()

estado_texto_ocr
ok                       2248
error_descarga_bucket     696
texto_muy_corto            37
vacio                       5
Name: count, dtype: int64

In [48]:
pd.crosstab(df_csv["clasificacion"], df_csv["estado_texto_ocr"])

estado_texto_ocr    error_descarga_bucket   ok  texto_muy_corto  vacio
clasificacion
Defensa Consumidor                    151  559                9      0
Embargo                               209  627                8      4
Juicio                                135  455                6      1
Mediación                              67  153                2      0
Oficio                                122  428               12      0
SECLO                                  12   26                0      0

# Qué faltaría explorar antes de cerrar CSV
A. Distribución de nombre

In [51]:
df_csv["nombre"].value_counts(dropna=False)

nombre
Embargo - usuario                                    843
Talonarios de Seguimiento                            619
Intimacion                                           420
Solicitud de informacion de usuarios                 340
Mediacion                                            222
Audiencia                                            203
Demanda                                               89
Notificacion procesal                                 88
Reclamo                                               53
SECLO                                                 38
Carta Simple                                          26
Solicitud relacionada con acceso a la informacion     17
Requerimiento                                         10
Propiedad Intelectual                                  5
Embargo - Empleado                                     5
Imputacion administrativa                              4
Allanamiento                                           3
Solicitud de información de empleado                   1
Name: count, dtype: int64

### Esto sirve para entender cómo se relacionan nombre y clasificacion.

In [52]:
pd.crosstab(df_csv["clasificacion"], df_csv["nombre"])

nombre,Allanamiento,Audiencia,Carta Simple,Demanda,Embargo - Empleado,Embargo - usuario,Imputacion administrativa,Intimacion,Mediacion,Notificacion procesal,Propiedad Intelectual,Reclamo,Requerimiento,SECLO,Solicitud de informacion de usuarios,Solicitud de información de empleado,Solicitud relacionada con acceso a la informacion,Talonarios de Seguimiento
clasificacion,,,,,,,,,,,,,,,,,,
Defensa Consumidor,0,0,26,0,0,0,4,0,0,0,0,53,0,0,0,0,17,619
Embargo,0,0,0,0,5,843,0,0,0,0,0,0,0,0,0,0,0,0
Juicio,0,0,0,89,0,0,0,420,0,88,0,0,0,0,0,0,0,0
Mediación,0,0,0,0,0,0,0,0,222,0,0,0,0,0,0,0,0,0
Oficio,3,203,0,0,0,0,0,0,0,0,5,0,10,0,340,1,0,0
SECLO,0,0,0,0,0,0,0,0,0,0,0,0,0,38,0,0,0,0

# B. Largo de textos válidos

In [53]:
df_csv["largo_texto_ocr"] = df_csv["texto_ocr"].astype(str).str.strip().str.len()

df_csv.groupby("estado_texto_ocr")["largo_texto_ocr"].describe()

,count,mean,std,min,25%,50%,75%,max
estado_texto_ocr,,,,,,,,
error_descarga_bucket,696.0,46.000000,0.000000,46.0,46.00,46.0,46.00,46.0
ok,2248.0,4349.814947,8393.469502,66.0,1591.75,2938.5,4390.25,117896.0
texto_muy_corto,37.0,27.000000,0.000000,27.0,27.00,27.0,27.00,27.0
vacio,5.0,0.000000,0.000000,0.0,0.00,0.0,0.00,0.0

#### Para los validos
Esto te va a decir si los oficios y embargos tienen textos razonables o si algunos son extremadamente largos/cortos.

In [55]:
df_csv[df_csv["estado_texto_ocr"] == "ok"].groupby("clasificacion")["largo_texto_ocr"].describe()

,count,mean,std,min,25%,50%,75%,max
clasificacion,,,,,,,,
Defensa Consumidor,559.0,2435.345259,6748.705793,104.0,371.50,489.0,2036.00,98817.0
Embargo,627.0,3518.559809,1593.149253,627.0,2398.00,3305.0,4309.50,10929.0
Juicio,455.0,5941.237363,14277.504419,211.0,1731.00,2735.0,4144.50,117896.0
Mediación,153.0,5254.183007,2240.505812,332.0,3726.00,4816.0,6590.00,13170.0
Oficio,428.0,6256.609813,8708.002561,66.0,2975.75,4025.5,5583.50,109110.0
SECLO,26.0,996.423077,287.627561,419.0,794.75,1072.0,1143.25,1417.0

# C. Crear dataset objetivo
Esto ya te deja preparado el dataset real de trabajo.  
textos OCR válidos + clasificación Oficio o Embargo

In [56]:
df_csv_valido = df_csv[df_csv["estado_texto_ocr"] == "ok"].copy()

df_objetivo_csv = df_csv_valido[
    df_csv_valido["clasificacion"].isin(["Oficio", "Embargo"])
].copy()

print("Registros CSV originales:", df_csv.shape[0])
print("Registros válidos:", df_csv_valido.shape[0])
print("Oficios y embargos válidos:", df_objetivo_csv.shape[0])

df_objetivo_csv["clasificacion"].value_counts()

Registros CSV originales: 2986
Registros válidos: 2248
Oficios y embargos válidos: 1055

clasificacion
Embargo    627
Oficio     428
Name: count, dtype: int64

# Análisis final
## Análisis exploratorio del CSV

El archivo CSV contiene 2986 registros y 4 columnas originales: `id`, `texto_ocr`, `nombre` y `clasificacion`.

La columna principal para procesamiento es `texto_ocr`, ya que contiene el texto extraído por OCR de los documentos legales. La columna `clasificacion` permite identificar la categoría general del documento.

No se encontraron valores nulos en las columnas originales, por lo que todos los registros tienen identificador, texto OCR, nombre y clasificación.

La distribución por clasificación muestra que la base contiene más tipos de documentos además de oficios y embargos:

- Embargo: 848
- Defensa Consumidor: 719
- Juicio: 597
- Oficio: 562
- Mediación: 222
- SECLO: 38

La detección inicial de HTML encontró muy pocos casos posibles, por lo que el problema principal del CSV no parece ser HTML, sino ruido propio del OCR: caracteres mal reconocidos, palabras deformadas, saltos de línea, textos incompletos y errores técnicos.

Se detectaron 738 textos legales duplicados. Al inspeccionar ejemplos, muchos corresponden a textos vacíos o mensajes como `Error al descargar el archivo desde el bucket.`, por lo que no deben interpretarse automáticamente como documentos legales repetidos.

Se creó una clasificación auxiliar del estado del texto OCR:

- ok: 2248 registros
- error_descarga_bucket: 696 registros
- texto_muy_corto: 37 registros
- vacio: 5 registros

Para el objetivo inicial de la pasantía, los documentos más relevantes son `Oficio` y `Embargo`. Luego de filtrar solo textos OCR válidos, quedan:

- Embargo: 627 registros válidos
- Oficio: 428 registros válidos

Por lo tanto, el dataset objetivo inicial para limpieza y procesamiento contiene 1055 registros válidos de oficios y embargos.

# Etapa 2 — Lectura guiada de oficios y embargos
Objetivo: Analizar ejemplos reales de Oficio y Embargo para definir qué información importante aparece en cada tipo de documento.

# Crear muestras para leer

In [57]:
# Muestras reproducibles para lectura manual
muestra_oficios = df_objetivo_csv[
    df_objetivo_csv["clasificacion"] == "Oficio"
].sample(n=10, random_state=42)

muestra_embargos = df_objetivo_csv[
    df_objetivo_csv["clasificacion"] == "Embargo"
].sample(n=10, random_state=42)

print("Muestra oficios:", muestra_oficios.shape)
print("Muestra embargos:", muestra_embargos.shape)

Muestra oficios: (10, 8)
Muestra embargos: (10, 8)

# Mostrar ejemplos de oficios

In [58]:
for i, row in muestra_oficios.iterrows():
    print("=" * 100)
    print("TIPO: OFICIO")
    print("ID:", row["id"])
    print("NOMBRE:", row["nombre"])
    print("CLASIFICACION:", row["clasificacion"])
    print("=" * 100)
    print(str(row["texto_ocr"])[:4000])
    print()

====================================================================================================
TIPO: OFICIO
ID: 546322
NOMBRE: Solicitud de informacion de usuarios
CLASIFICACION: Oficio
====================================================================================================
236
pola 13

OFICIO JUDICIAL
Buenos Aires, de marzo de 2026

MERCADOLIBRE SRL
Av. Caseros 3039, Piso 2 —- CABA.
Ss J D

Tengo el agrado de dirigirme a Ud. en mi carácter de letrado de la parte actora en el
expediente caratulado “DE LOS SANTOS, PABLO ROBERTO C/ GIMENEZ, PABLO
FABIAN Y OTROS S/DAÑOS Y PERJUICIOS(ACC.TRAN. C/LES. O MUERTE)” (Expte.
43264/2021) que tramita en el Juzgado Nacional en lo Civil N*65, sito en Inmigrantes 1950
piso 6?, CABA, a cargo de la Dra. María Gabriela FERNANDEZ ZURITA, Secretaría única a
cargo del Dr. Diego Martín DE LA IGLESIA. Se ha dispuesto a dirigir a Ud. el presente a fin
de solicitarle que informe el último domicilio registrado del señor Cairo CLAROS PATZI DNI
93.946.731.

El auto que ordena la medida dice así en su parte pertinente: “Buenos Aires, 16 de
diciembre de 2025 (...) Sin perjuicio de destacar que ya ha sido ordenada la publicación de
edictos, líbrense los oficios que se solicitan en los términos del artículo 400 del CPCCN.” Fdo.
LEONARDO BONETTI FRANCO, Sr. Prosecretario Administrativo Interino.

Se deja constancia que el presente expediente cuenta con un incidente de Beneficio
de Litigar Sin Gastos.

Art. 396 CPCCN: Los informes que se soliciten a las oficinas públicas, escribanos con
registro y entidades privadas deberán versar sobre hechos concretos, claramente
individualizados, controvertidos en el proceso. Procederán únicamente respecto de actos o
hechos que resulten de la documentación, archivo o registros contables del informante.
Asimismo, podrá requerirse a las oficinas públicas la remisión de expedientes.

Art. 398 CPCCN: Las oficinas públicas y las entidades privadas deberán contestar el
pedido de informes o remitir el expediente dentro de los diez días hábiles, salvo que la
providencia que lo haya ordenado hubiere fijado otro plazo en razón de la naturaleza del juicio
o de circunstancias especiales. No podrán establecer recaudos que no estuvieran autorizados
por ley. Los oficios librados deberán ser recibidos obligatoriamente a su presentación. El juez
deberá aplicar sanciones conminatorias progresivas en el supuesto de atraso injustificado en
las contestaciones de informes...

Se autoriza a diligenciar el presente a los Dres. Patricio Martin, Hernán F. Grisi y/o
Adrián Franco, y/o Julia Pestorino y/o Camila Jurado y/o Candela Caminos y/o M. Emilse
Zancarini y/o quienes ellos designen, indistintam

Saludo a udxmuy atentamente.

19 MAR 2026
RECEPCION

Taza ina


1]
= la o pumas as _
=> = ===
pa aa cs rr TNA TE TT: — pa
A :
«
: Í
A E ee
E Q ; Y or
E 3 mr
: É 4 al d q.
So E Fi
O 5 Cc e
Ó « y 7
2 3» v
Ss 72 ha pe o
E t $4 Pe
ñ ñ ; "S
- E “e o
O -N a Ls e - a a
del
¡e
E
O
Ol
Mas]
E
S A E - E 5 Ed A y
A a A
nf
2
2
2 — —



====================================================================================================
TIPO: OFICIO
ID: 503816
NOMBRE: Solicitud de informacion de usuarios
CLASIFICACION: Oficio
====================================================================================================
47/12/25, 4b:b1 p.m.

TEXTO

Organismo:

AL SEÑOR
S/D

S/APREMI
cual ¡se en
Judicial de
necesario

cuenta -baj
caso, infor
y montos c

7462/2022,
dinero elec:
Nicolas Jor
Art. (45 Le
administrati
Se encuen
Martín Ga
Navarro y/
Saludo a U

290 linc. b
respuesta

Usuario con

am

DATOS DE L/'A NOTIFICACIÓN

ORELLANA Felix Eugenio - 20136131169Qnotificaciones.scba.gov.ar
SECRETARIA DE APREMIOS - LA PLATA

17/12/2025 12:06:54

Firmado 25d) | ZUCCOL!I Maria Eugenia. AUXILIAR LETRADO --- Certificado Correcto. [Fl
| 17/12/2025 12:06:54

AAA)

OFICIO JUDICIAL
La Plata, en la fecha de
(GERENTE DE MERCADO PAGO

", que tramitan por ante este Juzgado de Primera Instancia en lo Civil y Co
entra a cargo del Dr. Nicolas Jorge Negri, Secretaria de Apremios, d

ra que se informe si VILLARREAL ROSANA GABRIELA DNI 21.395.830, [e
la modalidad de "billetera electrónica” (o billetera virtual)- a su nombre y/o de

el tipo, número de cuenta y/o identificación de la misma, indicando en
respondientes

le Negri, Juez”.-
7014: "La Caja estará exenta de todo impuesto y tasa de sellos en
a y ¡judicial".-

la Sahd y/o Pablo Hernán Urriza y/o Maria Eugenia Scanavino y/o | y/
quien legalmente designen para sustituirlos a tal efecto.

. atte.-

Carátula: CAJA DE PREVISION SOCIAL PARA MARTILLEROS Y CORREDORES PÚBLICOS C/
VILLARREAL ROSANA GABRIELA S/ APREMIO |
Número de chusa! 14-212474
Tipo de noti ación: OFICIO A
Destinatario | 201361311690 notificaciones.scba.gov.ar
Fecha notificación: 19/12/2025
Alta j disponibilidad 47/12/2025 12:06:55
Firma digital!| Firma válida
Firmado y slnclos por: ZUCCOLI Maria Eugenia. AUXILIAR LETRADO -— Certificado Correcto:
¡

echa de Firma:

la firma digital.

Tengo el agrado de dirigirme a Ud. en los autos caratulados "CAJA/DE|PREVISION
SOCIAL P MARTILLEROS Y CORREDORES PUBLICOS C/ VILLARREAL ROSANA GABRIELA
ercial nro. 14 el
|

epartamento

a Plata, sita en calle 14 N* 682; a fin de que por quien correspondal Ss disponga lo

sititular de una
ctivo y, en su
lu caso CVU

El auto que ordena el presente dice así: "La Plata, 09 de octubre de 2025. Téngase

presente lo[manifestado, y en orden a ello, líbrense los oficios a las billeteras virtuales |solicitadas -
Mercado He Cuenta DNI, Ualá, Modo, y Naranja X-, como empresas proveedoras d servicios de
pagos| (PSP) ylo entidad financiera, para que informe si ROSANA GABRIELA VI AREA DNI
21.395.830!lles titular de una cuenta -bajo la modalidad de "billetera electrónica" (o sele virtual)- a su
nombre y/o pe activo y, en su caso, informe el tipo, número de cuenta y/o identificación [de la misma,
indicando eh su caso CVU y montos correspondientes (art. 34, inc. 5*, CPCC; cfr, Comunicación "A"

BCRA; Negri, Nicolás J., "Plataformas de servicios financieros: Billetefas| electrónicas,
ónico y criptoactivos; la defensa del consumidor", Rubinzal Online, RC D! 248/2023). Fdo.

su actuación

an lautorizados para su diligenciamiento el Doctor Félix Eugenio Orellana |y/o los Sres.

Romina Pérez

y cc. CC y CN; art. 1,2 y cc Res. SCBA 386/20; Res. SCBA 14/20 y|4039/21). La

El presenté oficio se encuentra firmado digitalmente en los términos de la Ley 2 506 y arts. 288,
la, ser enviada como presentación electrónica en el marco de estas actuaciones.

) ¡IO NOTIFICACIÓN - SUPREMA CORTE DE JUSTICIA - NOTIFICACIONES L.eómoónicas -

https://notificacionekiscba.gov.ar/InterfazBootstrapltextonotificacionimprimir.aspx?2idnot=1 361787848fecha=2

112


17/12/25, 12:21 p.m. TEXTO Y DATOS DE LA NOTIFICACIÓN - SUPREMA CORTE DE JUSTICIA - NOTIFICACIONES ELECTRÓNICAS

Para verificar la notificación, y las copias de traslado si las hubiere, ingrese a:
https://notificaciones.scba.gov.ar/verificar.aspx
Su código de verificación es: KTOMK7NY

A

222801554031233311

https://notificaciones.scba.gov.ar/InterfazBootstrap/textonotificacionimprimir.aspx?idnot=1361787848fecha=2 212


====================================================================================================
TIPO: OFICIO
ID: 520978
NOMBRE: Solicitud de informacion de usuarios
CLASIFICACION: Oficio
====================================================================================================
CARATULA DE NOTIFICACION

SISCOM (NO UTILIZAR, SOLO PERMITE RESPUESTAS) Pbder

Mercado Libre S.R.L
CASEROS AV. 3039 2
Común

555553

POCAS

PODER JUDICIAL DE LA NACION
DIRECCIÓN GENERAL DE NOTIFICACIONES

GARCIA MARCELO ALEJANDRO S/ SUCESION AB-

ZONA 0034

RECIBIDO

A
815 6
|

(2

INFORME DEL OFICIAL NOTIFICADOR ——— mn RO A

CEDULA DIRECTA DE NOTIFICACIÓN

nr AN ll |

CEDULA DIRECTA N*:

copia Documental digitalizada

«gado Civil Numero 5 JNQCI5-EXP-555553 /2924

ATARIO:
o Libre S.R.L
ulq: OTROS

ección: Av. Caseros 3839, Ciudad Autónoma de Buenos Aires, Argentina, Pisd
Had [Autónoma de Buenos Aires. , Buenos Aires (LEGAL)

spber a Ud. que en los autos caratulados: "GARCIA MARCELO ALEJAND
a AB INTESTATO”, 555553/24, en trámité por ante el Juzgado de 1% Ins

ara, [Secretaría Única, sito en calle Almirante Brown N' 115, de la ciud

NUEN ; se ha dispuesto notificarle la providencia ordenada, que dice: “Nebdué

He [Octubre del año 26825... En consetuencia, dispóngase el cambi
efcibimiento prevista en la providencia de fecha 17/82/25 (fs.

dad con el art. 37 del CPCyC. Eh virtud. delo anterior,.: in
qyemente a Mercado Libre S.R.L., en el domicilio legal siito en Av. Caseros
j 2,| Ciudad Autónoma de Buenos Aires, para que; dentro" del "plazo de DIEZ

28 ly 922548, bajo apercibimiento de imppnérsele unam (

fyía (que estimen más idónea (correo electrónico o icial;.-correspondencia
Fma presencial).” Fdo. MARIA GUADALUPE LOSADA, ¡Jueza.- cil
4 dar cumplimiento a los términos previstos por la 16y 32172.

: MARIA GUADALUPE LOSADA
EREZ MARIA ISABEL
HANTE: GARCIA MARCELO ALEJANDRO
HETENCIA: Juzgado de 1% Instancia en lo Civil, Comercial y de Mineria n* 5
BRIA! SUCESIÓN AB INTESTATO
TADOS: Los Dres. Luis Alberto Lopez y/o Hernan Daniel Minetto y/o
ina|Belén Lopez y/o Srta. Mariela Lopez y/o Cid Franco Nahuel y/o Costa

gentiamiento de la presente.
adjuntan copia de oficios N” 751387, 794729, 892228 y 922548

A UD. DEBIDAMENTE NOTIFICADO. -

20 FEB 20%

ivil, Comercial y de Minería N% 5 a pargo de Dra. María Guadalupe Lb

sipituyéndolo por el de aplicación de astréeintes en caso de incumplimiento
114 3

dé notificada cumpla con lo requerido, en lós oficios Aa 404 4
Lt e no

41.464,05) por única vez. A tal fin, líbrese hueva cédula con _copia” Hb
egente, autorizándose a los letrados interviniente pala..su- diTigenciamiento|

ENZO| y/ o quienes ellos designen, se encuentran facultados park


LUGAR Y FECHA: NEUQUEN, VIERNES 6 DE FEBRERO DE 2826

A los fines pertinentes, se indica que la presente CEDULA DIRECTA se libra
conforme a la Reglamentación del Sistema de Seguimiento de Cédulas, Oficios y
Mandamientos aprobado por el Tribunal Superior de Justicia mediante Acuerdo N”
5831, pto. 23 y sus modificatorias, y Acuerdo N” 6428 punto 12 que aprueba la
incorporación al Bus Federal para los casos de las provincias adheridas al mismo y
comunicaciones con firma digital para las no adheridas. Asimismo su autenticidad y
contenido puede ser verificado mediante el mecanismo que aparece al pie del
presente, en el sitio oficial del Poder Judicial.

Acceda a "https://exd.jusneuquen.gov.ar/validar_documento” e ingrese el código
4eGNDAXBK para verificar la autenticidad de la cedula, y acceder a las copias de
trabplado que se hubieran adjuntado a la diligencia.

374B74025965ae1e97841764114abbf386fcffe881cb48fbbBdaaLcde80f192f DS


====================================================================================================
TIPO: OFICIO
ID: 498355
NOMBRE: Audiencia
CLASIFICACION: Oficio
====================================================================================================
GENERAL LA MADRID, 2 de enero de 2026

EAS mercado
Sr. MERCADO LIBRE SRL : ES More
Av. Caseros 3039 2” piso Buenos Aires

notificaciones(A)lla.com.ar
S / D

43 ENE 2026
4-

"RECEPCION
Me dirijo a usted a fin de comunicarle que el día 23 de enero de

2026, a las 10:00 hs. deberá concurrir ante esta OFICINA MUNICIPAL

DE INFORMACION AL CONSUMIDOR, sita en calle San Martin 831

de la ciudad de General La Madrid, el representante legal de

“MERCADO LIBRE SRL” , acreditando dicha condición con poder

suficiente (fotocopia de Poder para ser adjuntada a las actuaciones) a la

audiencia fijada con motivo del reclamo que tramita bajo de Expediente

N' 3397 efectuado ante este Organismo por el Sr. GOÑI GONZALEZ,

Benjamin D.N.I: 47.140.450 quien manifiesta la siguiente situación que

al momento de realizar un trámite, toma conocimiento de su la situación que

arroja el BCRA con Mercado Libre SRL, que el mismo reconoce haber

solicitado un préstamo, pero que por motivos ajenos no pudo cancelar el mismo

en tiempo y forma, que es su intención regularizar dicha situación por lo que

solicita que informe el monto para cancelar y modificar el informe en BCRA.-

ray ma AA

Lo dispuesto halla su sustento en el Artículo 1% y concordantes y Artículo 45%
.segundo párrafo y Artículo 44” de la Ley Nacional N*24.240 de Defensa del
Consumidor y Artículos 46? y 47" de la ley 13.133 el último de los artículos que
para su conocimiento se transcribe a continuación: “...notificada la audiencia
el denunciado no compareciere sin causa justificada, se formulará auto de
imputación...”

ARTICULO 44* de la Ley Nacional N*24.240: "Auxilio de la fuerza
pública. Para el ejercicio de las atribuciones a que se refieren los incisos
d) y f) del Artículo 43% de la presente Ley, la Autoridad de Aplicación
podrá solicitar el auxilio de la fuerza pública."

ARTICULO 46" Ley Provincial N* 13.133: "Recepcionada la denuncia se
abrirá la instancia conciliatoria a cuyos fines se designará audiencia, La
notificación de la misma se hará por escrito. ---ooamccnnnicccnnnaanncanionas

e ---QUEDA UD. DEBIDAMENTE NOTIFICADO.---.===-

OFICINA MUNICIPAL DE INFORMACION AL CONSUMIDOR

Calle: San Martin 831

(7406) General La Madrid

HORARIO DE ATENCION: 7:00 a 13:00 hs.
E-mail: mgl.omictgmail.com Dre. CINTIA

yu 05012022 6 1
AT




====================================================================================================
TIPO: OFICIO
ID: 542264
NOMBRE: Solicitud de informacion de usuarios
CLASIFICACION: Oficio
====================================================================================================
9/3/26, 9:40 TEXTO Y DATOS DE LA NOTIFICACIÓN - SUPREMA CORTE DE JUSTICIA - NOTIFICACIONES ELECTRÓNICAS J
TEXTO Y DATOS DE LA NOTIFICACIÓN

Usuario conectado: PONCE Cristian Jorge - 20297083431Qnotificaciones.scba.gov.ar
Organismo: JUZGADO EN LO CIVIL Y COMERCIAL N? 4 (EX JCC N*1) - LANUS
Carátula: MAZZAFERRO LUCIANO DANIEL S/ BENEFICIO DE LITIGAR SIN GASTOS
Número de causa: 67859
Tipo de notificación: OFICIO ELECTRONICO

Destinatarios: 20297083431 Qnotificaciones.scba.gov.ar,

2029708343109 NOTIFICACIONES.SCBA.GOV.AR

Fecha notificación: 09/03/2026 08:52:27

Alta o disponibilidad 9/3/2026 08:52:28

Firma digital: Firma válida

Firmado y Notificado por: NATIELLO Marcelo Alfredo. SECRETARIO --- Certificado Correcto. Fecha de Firma:
09/03/2026 08:52:27

Firmado por: PONCE Cristian Jorge. --—- Certificado Correcto. Fecha de Firma: 04/03/2026 09:24:33

OFICIO mesada
Lanus, 04 de marzo de 2026 3 1 6 PAR 2026
MERCADO PAGO a mm
Ss / D.- RECEPCION

Tengo el honor de dirigirme a Usted en mi carácter de letrado patrocinante en
llos autos caratulados en los autos caratulados “MAZZAFERRO LUCIANO DANIEL S/ BENEFICIO DE
LITIGAR SIN GASTOS” Nro. de Expte.: 67859, en trámite por ante el Juzgado en lo Civil y Comercial
Nro 4, del Departamento Judicial de Avellaneda / Lanús, ubicado en calle 29 de septiembre de 1890 de
la Localidad y Partido de Lanus, a fin de que informe la titularidad de cuentas bancarias a nombre
de MAZZAFERRO LUCIANO DANIEL DNI 38.841.006. Hágase constar en el oficio a librarse la
iniciación del presente beneficio litigar sin gastos y que, de conformidad con lo establecido
por el art. 80 del CPCC., el mismo se encuentra exento del pago de todo tipo de arancel,

El auto judicial que ordena el presente en su parte pertinente dice:'Lanus 23
de Febrero de 2026. Hágase saber al peticionante que atento la respuesta al oficio a BCRA que se
encuentra agregada a las presentes actuaciones ( ver fs. 25), previo a lo solicitado, deberá librar los
oficios a las entidades bancarias informadas a los fines de que éstas informen si la parte actora resulta
ser titular de cuentas de cualquier naturaleza y en su caso detalle de las mismas, dejándose expresa
constancia en las piezas a librarse la circularización de lo requerido a través de la comunicación "Da
todas las entidades reguladas. Hágase constar en el oficio a librarse la iniciación del presente beneficio
de litigar sin gastos y que, de conformidad con lo establecido por el art. 80 del CPCC., el mismo se
encuentra exento del pago de todo tipo de arancel. Fdo. Dr. Guillermo A. Oyhanart Juez Firmado
electrónicamente -

ARTÍCULO 396*: Recaudos y plazos para la contestación. Las oficinas públicas no podrán establecer
recaudos o requisitos para los oficios sin previa aprobación por el Poder Ejecutivo, ni otros aranceles
que los que determinen las leyes, decretos u ordenanzas.

| Deberán contestar el pedido de informes o remitir el expediente dentro de 20 días hábiles y las |
| entidades privadas dentro de 10, salvo que la providencia que lo haya ordenado hubiere fijado otro
plazo en razón de la naturaleza del juicio o de circunstancias especiales.

ARTÍCULO 397": (Texto según Ley 14365) Retardo. Si por circunstancias atendibles el requerimiento
no pudiere ser cumplido dentro del plazo, se deberá informar al Juzgado, antes del vencimiento de
aquél, sobre las causas y la fecha en que se cumplirá.

Isi el Juez advirtiere que determinada repartición pública, sin causa justificada, no cumple
reiteradamente el deber de contestar oportunamente los informes, deberá poner el hecho en
conocimiento del Ministerio de Gobierno, a los efectos que correspondan, sin perjuicio de las otras

https://notificaciones.scba.gov.ar/InterfazBootstrap/textonotificacionimprimir.aspx2idnot=1411843678techa=28codNotif= 112


9/3/26, 9:40 TEXTO Y DATOS DE LA NOTIFICACIÓN - SUPREMA CORTE DE JUSTICIA - NOTIFICACIONES ELECTRÓNICAS |

medidas a que hubiere lugar. |

A las entidades privadas que sin causa justificada no conte

====================================================================================================
TIPO: OFICIO
ID: 532434
NOMBRE: Audiencia
CLASIFICACION: Oficio
====================================================================================================
UNICIPALIDAD
Í DE GENERAL PICO

Oficina de Defensa del Consumidor
CEDULA de NOTIFICACION de AUDIENCIA

4y Cuc4zezarr 5 Il BADO JUAN CARLOS BENITO C/

Ñ MN II ADMIN) III], MERCADO LIBRE s/ RECLAMO LEY 24240

CAUSA N” 1842/2026

Sr./a Denunciada: MERCADO LIBRE

Avda. Caseros N.” 3039

Parque Patricios - BUENOS AIRES COD. POS: 1264
DOMICILIO ELECTRONICO: dde(Omercadolibre.com

Se le hace saber que en la actuación de referencia, en trámite ante la Oficina de Defensa
del CONSUMIDOR, sita en calle Ruta 1 Esquina. Avda. San Martín Oficina. 3/4 (Terminal de
Ómnibus) de la ciudad de General PICO (La Pampa), se ha dictado lo siguiente: POR ELLO: LA
OFICINA DE DEFENSA DEL CONSUMIDOR DISPONE: ARTICULO 1: Téngase por
presentada la denuncia efectuada por: BADO JUAN CARLOS BENITO por presunta infracción a la
Ley 24240 de Defensa del CONSUMIDOR, que involucra a la Empresa: MERCADO LIBRE. Cítese
a las partes a la audiencia de Conciliación prevista en el Art. 45 de la Ley 24240, la que se realizará
ante la Oficina de Defensa del CONSUMIDOR, sita en calle Ruta 1 Esquina. Avda. San Martín Oficina
3y4 (Terminal de Ómnibus) de la ciudad de General PICO, el día 19 de MARZO de 2026 a las 9:00
horas.- Los comparecientes deberán acreditar su identidad con DNI., C.I, o LE., y , en caso de invocar
mandato demostrarlo en forma legal. ARTICULO 3: Notifíquese al denunciante que en el' acto de la
audiencia deberá acompañar la documentación original de todo instrumento relacionado con el caso a
fin de efectuar su compulsa con los agregados a autos y su certificación. ARTICULO 4: En caso de
incomparecencia injustificada de las partes, la autoridad de aplicación podrá requerir su

presencia mediante el auxilio de la fuerza pública (Art.44 de la Ley 24240). A los fines
informativos de las partes se hace saber lo siguiente:

ART 47? SANCIONES: Verificada la existencia de la infracción, quienes la hayan cometido se harán pasibles de las siguientes sanciones, las que se

# Mostrar ejemplos de embargos

In [59]:
for i, row in muestra_embargos.iterrows():
    print("=" * 100)
    print("TIPO: EMBARGO")
    print("ID:", row["id"])
    print("NOMBRE:", row["nombre"])
    print("CLASIFICACION:", row["clasificacion"])
    print("=" * 100)
    print(str(row["texto_ocr"])[:4000])
    print()

====================================================================================================
TIPO: EMBARGO
ID: 544832
NOMBRE: Embargo - usuario
CLASIFICACION: Embargo
====================================================================================================
OFICIO JUDICIAL

/ L/)

Buenos Aires, de Febrero/de/2026
Al Sr. Apoderado de |
“MERCADO LIBRE S.R.L.”
S / D

De mi consideración:

Tengo el agrado de dirigirme a Ud. en los autos
caratulados “CHUQUISACA, SERGIO HORACIO C/ MENUDENCIAS
S.A, Y OTROS S/ DESPIDO ", Expediente. Nro. 21903/14, que tramita
por ante el Juzgado Nacional de Primera Instancia del Trabajo Nro. 35, sito
en la calle Tte. Gral. Juan D. Perón 990 Piso 7mo. de C.A.B.A., a mi cargo,
Secretaría única a cargo del DR. MARIANO GILLETTE TORRILLA,
para informarle que se ha decretado embargo sobre bienes de la demandada
“FAENADORA ARGENTINA S.A.” CUIT 33-71237566-9 hasta cubrir la
suma de $ 31.177,68.- (en concepto de honorarios del perito contador), con
más la de $9.000.- presupuestados provisoriamente para responder a
IMÍOreSES Y COSÍAS occ

Se le hace saber que deberá retener de las sumas que tenga la embargada
depositadas en esa entidad, por cualquier concepto, presentes y /o futuros,
los montos indicados ut supra. Dichos importes deberán ser transferidos
dentro de las 48 horas de retenidos al BANCO DE LA CIUDAD DE
BUENOS AIRES, SUCURSAL TRIBUNALES, a la orden de V.S. y como
pertenecientes a estos autos, estando abierta dicha cuenta según los
siguientes datos: C.B.U. 02900759-00294149207615 - CUIT Banco Ciudad
30-99903208-3 y Clave 0006-035- -1492-0761-4 . Asimismo, dentro de los
cinco días de recepcionado el oficio deberá informar al Juzgado el resultado
de la gestión encomendada. ono

Sin otro particular lo saludo muy atentamente

mercado DR. ALBERTO A,
libre 0
Signature ot Verified
Digltaly ¿tened lARIA JOSE 18 MAR 2026

Date: 2026.02.09 18:51:59 ART

¿
RECEPCION '

Torr

| (ariano h. fillette
| SECRETARI



====================================================================================================
TIPO: EMBARGO
ID: 546230
NOMBRE: Embargo - usuario
CLASIFICACION: Embargo
====================================================================================================
A

+ 19 MAR 2026 |

+
1
É

RECEPCION

e
Poder Judicial de la Nación
JUZGADO CIVIL 7

40471/2023

VASSALLO, FERNANDO c/ BENITEZ, MARIA ANGELICA
s/ALIMENTOS

Buenos Aires, de marzo de 2026.- MEG
OFICIO REIFERATORIO

Mercado Pago
Assetmanagement SA
S / D

Tengo el agrado de dirigirme a Ud. en los autos
caratulados: “VASSALLO, FERNANDO C/ BENITEZ, MARIA
ANGELICA S/ALIMENTOS” expte n* 40471/2023 que tramitan ante
el Juzgado Nacional de Primera Instancia en lo Civil nro 7 a cargo de
la Dra Myriam Cataldi, Secretaría única a mi cargo, con domicilio en
la calle Talcahuano 490, Piso Sexto CABA (correo electrónico:
jncivil7Opjn.gov.ar) a fin de que proceda a trabar embargo sobre los
fondos pertenecientes al demandado, Sr. FERNANDO VASALLO,
DNI N* 20.891.829, que posea en dicha entidad financiera, ya sea
sobre fondos y valores depositados en cuenta corriente, caja de ahorro,
inversiones a plazo fijo, cuentas títulos, billeteras virtuales y cualquier
otro activo financiero, ya sean presentes o futuros, por la suma
de PESOS SIETE MILLONES SETECIENTOS VEINTE
MIL CUATROCIENTOS CINCUENTA Y NUEVE CON
CINCUENTA Y SIETE CENTAVOS ($7.720.459,57), con más la
suma de PESOS UN MILLON QUINIENTOS MIL ($1.500.000). Las
sumas resultantes deberán depositarse en la cuenta abierta en el Banco
de la Nación Argentina, Sucursal Tribunales, a nombre de estos autos
y a la orden de este juzgado, n* 9989744557, CBU
0110025950099897445578, debiendo comunicar al Tribunal la traba
de la medida y el monto de la suma embargada.

11279194 3849306869220260311125510861


El auto que ordena la medida en su parte pertinente dice “
Buenos Aires 3 de diciembre de 2025. AUTOS Y VISTOS: (...) Sin
perjuicio de ello, de conformidad con lo previsto por el art. 550
CCyC, que prevé la traba de medidas cautelares para asegurar el pago
de alimentos futuros, provisionales, definitivos o convenidos, por la
suma de PESOS SIETE MILLONES SETECIENTOS VEINTE MIL
CUATROCIENTOS CINCUENTA Y NUEVE CON CINCUENTA
Y SIETE CENTAVOS ($7.720.459,57), con más la suma de PESOS
UN MILLON QUINIENTOS MIL ($1.500.000) que se presupuestan
provisoriamente para responder a intereses y costas, trábese embargo
sobre los fondos pertenecientes al demandado, Sr.
FERNANDO VASALLO, DNI N* 20.891.829, que posea en
cualquiera de las entidades bancarias y financieras que operan en la
República, ya sea sobre fondos y valores depositados en cuenta
corriente, caja de ahorro, inversiones a plazo fijo, cuentas títulos,
billeteras virtuales y cualquier otro activo financiero, ya sean
presentes o futuros. (...) Las sumas resultantes deberán depositarse
en la cuenta abierta en el Banco de la Nación Argentina, Sucursal
Tribunales, a nombre de estos autos y a la orden de este juzgado, n*
9989744557, CBU 0110025950099897445578. (...) líbrese oficio a
Mercado Pago Assetmanagement SA y Mercado Libre. (...)". Fdo:
Myriam M. Cataldi. Jueza Nacional en lo Civil. Buenos Aires, de 2
febrero de 2026.- En atención a lo solicitado y lo que surge de la
constancia agregada, líbrese nuevo oficio a Mercado
Pago Assetmanagement SA y Mercado Libre, haciéndole saber el
carácter de reiteratorio de su similar recepcionado el 18/12/25, bajo
apercibimiento de lo dispuesto por el art. 3983 del Código Procesal.-"
Fdo: Myriam M. Cataldi. Jueza Nacional en lo Civil.

Art. 398. - Las oficinas públicas y las entidades privadas deberán contestar el
pedido de informes o remitir el expediente dentro de los diez días hábiles, salvo
que la providencia que lo haya ordenado hubiere fijado otro plazo en razón de la
naturaleza del juicio o de circunstancias especiales. No podrán establecer
recaudos que no estuvieran autorizados por ley. Los oficios librados deberán ser
recibidos obligatoriamente a su presentación. El juez deberá aplicar sanciones
conminatorias progresivas en el supuesto de atraso injustificado en las

contestaciones de informes. La apelación que se dedujera contra la resolución que

$+37919438114930686921420260311125510861

18

Poder Judicial de la

====================================================================================================
TIPO: EMBARGO
ID: 543050
NOMBRE: Embargo - usuario
CLASIFICACION: Embargo
====================================================================================================
TEXTO Y DATOS DE LA NOTIFICACIÓN

[
| Usuario conectado:

MINGIACA GABRIEL ALEJANDRO - 202610119308 nofificaciones.scba.gov.ar

| Organismo: JUZGADO DE FAMILIA N? 5 - SAN ISIDRO
| Carátula: MUGUILLO GERVASIO CAMILA SOLEDAD C/ GOMEZ DIEGO JAVIER S/ EJ
| SENTENCIA 1
Número de causa: SI-38561-2022 ¡
Tipo de notificación: OFICIO ELECTRONICO A |
Destinatarios: 20261011930Qnotificaciones.scba.gov.ar
Fecha notificación: 13/3/2026
Alta o disponibilidad 42/3/2026 12:20:08 ARE A
Firma digital: Firma válida | RECIBIDO
Firmado y Notificado por: ELHELOU Fernando Gabriel. SECRETARIO — Certificado Correcto. Fecha de Firma: 12/03/2026
12:20:05
Firmado por: ELHELOU Fernando Gabriel. SECRETARIO — Certificado Correcto. Fecha de Firma: 12/03/2026
12:20:04

OFICIO

San Isidro, en fecha de firma electrónica.-

MERCADO PAGO
SID

Tengo el agrado de dirigirme a Ud. en relación a los autos caratulados "MUGUILLO GERVASIO
CAMILA SOLEDAD C/ GOMEZ DIEGO JAVIER S/ EJECUCION DE SENTENCIA" Expte: SI - 38561 - 2022, en
| trámite por ante el Juzgado de Familia N* 5, Departamento Judicial de San Isidro, a cargo de la Dra. GRILLO
¡Juana Maria - JUEZ, Secretaría única, a cargo de los Dres, María Sol Bacman Ravera y Fernando Gabriel
¡Elhelou, sito en Av. Centenario 1860, San Isidro, Provincia de Buenos Aires, con domicilio electrónico:
juzfam5-siOjusbuenosaires.gov.ar, a los fines de solicitarle la traba de embargo en relación al Sr. DIEGO
JAVIER GOMEZ, DNI N? 27.270.953, en la billetera virtual Mercado Pago (CVU 0000003100087743731453) por la
suma de $14.309.175 (PESOS CATORCE MILLONES TRESCIENTOS NUEVE MIL CIENTO SETENTA Y CINCO),
con más la suma de $7.200.000 (PESOS SIETE MILLONES DOCIENTOS MIL) presupuestada prima facie para
responde a intereses y costas del presente juicio, haciendo saber que dichos importes deberán ser depositados en
la cuenta judicial a orden de este Juzgado: BANCO PROVINCIA DE BUENOS AIRES. SUC.5099-SAN ISIDRO-
BANCO PROVINCIA BS AS. CUIT PODER JUDICIAL 30707216650. CBU: 0140136927509993898056.
Transcripción del auto que ordena la presente medida, en su parte pertinente: "San Isidro,
[26/02/2026.- Atento lo expuesto y conforme lo peticionado, siendo exacto lo señalado por la actora respecto a la
[inexistencia de fondos depositados en la cuenta judicial de autos (se adjunta constancia), ampliáse el
embargo que fuera trabado por resolución del 24/10/2025 sobre los fondos que por cualquier concepto posea el
[demandado -en el presente o futuro- en la billetera virtual de Mercado Pago (CVU 0000003100087743731453),
debiendo las sumas retenidas ser depositadas en la cuenta judicial abierta a nombre de autos y a la orden de este
Juzgado, en el Banco de la Provincia de Buenos Aires, Sucursal Tribunales de San Isidro
(CBÚ 0140136927509993898056), hasta cubrir la suma de $14.309.175 (pesos catorce millones trescientos nueve
mil ciento setenta y cinco), con más la suma de $7.200.000 (pesos siete millones docientos mil)
presupuestada prima facie para responde a intereses y costas".- Fdo. Dra. GRILLO Juana Maria - JUEZ.
"San Isidro, 11 de Noviembre del 2025. Nro. de Cuenta: 5099- 027-0938980/5  (Prop.: 768764)-
Juzgado: JUZGADO DE FAMILIA N 5. CUIT PODER JUDICIAL 30707216650 Denominación: MUGUILLO
[GERVASIO CAMILA SOLEDAD C/ GOMEZ DIEGO JAVIER S/ EJECUCION DE SENTENCIA. CBU:
10140136927509993898056. SUC.5099-SAN ISIDRO-BANCO PROVINCIA BS AS  (bcoprovinciaS099-
| sanisidro(Obapro.notificaciones) Fdo. TREBINO Mariano Javier - Organismos Externos.
Se deja constancia que se encuentra autorizado al diligenciamiento del presente el Dr. GABRIEL
ALEJANDRO MINGIACA, abogado inscripto en Tomo XLVII Folio 264 - C.A.S.!.
Saludo a Ud. atentamente.-

Para verificar la notificación, y las copias de traslado si las hubiere, ingrese a: https://notificaciones.scba.gov.ar/verificar.aspx
Su código de verificación es: ONN8NE87

A eN

30


55 a A
an de ds Ma

Mc A MESÓN A dv CATA O TOO
A

po et

in

Ss O nes
PI a?
E

- ORATAR O aperos LATA
Mi?

ra le a cm DO EIA

ete

$

358


====================================================================================================
TIPO: EMBARGO
ID: 518820
NOMBRE: Embargo - usuario
CLASIFICACION: Embargo
====================================================================================================
a (la
, CART, . DOCUMENTO
DESTINATARIO
Primera Instancia
Comercial N* 9 MERCADO LIBRE S.R.L.
13
DOMICILIO
1 == >= — yda. € s N* 3039, Piso 2
Ez X= =WX= | LOCALIDAD PROVINGA
pe == =.1= 264A4 Ciudad Autónoma
Y [

 omcloreiliarmano.S..
| s. que en los autos caratulados “REZZET MA CIELO C/ GIECO ORLANDO MN
(Expte. N* 5013), en trámite por ante el ÓN do de Primera Instancia en lo Civil y
lraná, Provincia de Entre Ríos, a cargo del Dr. Angel Luis MOIA, Secretaría N* 2 Ni [)
W ha dispuesto librar el presente fin de informar que se ha decretado EMBARGO contfa
| .UL LT. N9 20-26858525-8, sobre los fondos ph ah y futuros que por cualquier concdp
en cal ¡ente hasta cubrir la suma total reclamada de hi 333.240,47, con más la de $ 1,30
provisd riamente intereses y costas; lo que hace un total de PESOS UN MILLON SEISCIENTOS C A
MIL E SENTA Y DOS CON TREINTA Y UN CENTAVOS ($ 1.641.162,31), la que deberá
i I| Nuevo Banco de Entre Ríos S.A. - py od Tribunales, Cuenta N* 62-208
0894723, como Lain al a estos autos y a A rden de S.S.--
ordenan el presente, en sus partes RAIN Y “PARANA, 6 de noviembre de
y edtrónica de fecha 04.11.2024, 09:32 hs.: Atento a lo manifestado, lo peticionado en k ]
'proved| y. exclusiva responsabilidad, decrétase embargo contra el ejecutado Orlando Jesús ( UIT. 20-
268587 8, 4 M e hará efectivo sobre los actuales y ANS hd por cualquier concepto el referido vupidaido pudiere

b diere t er,
84 estimada

Jesús

Ñ Í Q
E tener e MERC ROM da LIBRE 8, R.L., CUIT 30-70308853-4, con icilio en Avda. Caseros N* 3039, Pisp|2P|de CABA, en S
S 'cantid dj sufidid d Ihre hasta cubrir la suma total reclamada de PESOS TRESCIENTOS TREINTA Y T, ISCIENTOS
E CUARENTA a A q UARENTA Y SIETE CENTAVOS (8 333.240,47) con mas PESOS UN MILLON (Y ÑOS Abs =
BS MIL precia TO VEINTIUNO CON OCHENTA y CUATRO CENTAVOS (8 1.307.921,54) esthad y 2

Vente] intereses Y costas, la que deberá depositarse en cuenta judicial en la Sucursal Tribunales del
E ENTRI (os da a nombre del suscripto y como perenacene a estas actuaciones.- A los fines de la vb
librarsk ofici ey 22.172 correspondiente, quedando la confección y diligenciamiento a cargo de laliht:
deberdy “asimisppo <a ubirlos por módulo de presentaciones, a los fines de su control y nl -de

Procédase a ldllupe pa cuenta judicial para estas arca de debiendo incorporarse sus dat leon: a

ad * * Fd is Moia - Juez- “PARANA, 5 de febrero de 2026.- Proveyendo la presentaci trónic de

59 (92.0. 0:21 hs.-: Atento a lo manifestado, lo peticionado por la accionante, ya los fines okde

¡ ! e] nuevo ofi cio Ley 22.172 correspondiente ¡para la toma de razón, quedando)

Teriateresada, quien deberá, asimismo, subirlo por módulo de RT

E le correspondez-.” Edo.: Ángel Luis Moia - Juez. === 1
a CERINI y/o el profesional que ella designe se encuentran facu adds para d 14 p

AJúda : a Uds. muy ns ; - eS £ 2. p-!

CLIENTE CORPORATIVO

OLLS080LOy

E 20360757232 ||

? ANA
2 corra

AA
1 cosas

AAA 0

“IVNOIDVN
ua

/1 NNO3S 7 EZLGLO9E 09

INNIOA VISVI

JLNIDIA Oates

MÍ ounz



====================================================================================================
TIPO: EMBARGO
ID: 538081
NOMBRE: Embargo - usuario
CLASIFICACION: Embargo
====================================================================================================
8 UN 00000
100009755236

PODER JUDICIAL DE LA NACION
DIRECCIÓN GENERAL DE NOTIFICACIONES

CARATULA DE NOTIFICACION
Origen: JUZGADO EN LO CIVIL Y COMERCIAL N*10 - MAR DEL PL
Destinatario: MERCADO PAGO ASSET MANAGEMENT S.A.
Dirección: CASEROS AV. 3039 2
Caracter: Común
Expediente: MP-1493-2026
CHIAMINO WALTER RICARDO C/ BIERNVERT CLAUDIA
nJo3|z6 ZONA 0034
EZ A


INFORME DEL OFICIAL NOTIFICADOR ——— IgM A

CC Fecha de recepción en Ofic../
Deleg. o Juzgado de Paz

PODER JUDICIAL PROVINCIA DE BUENOS
AIRES
Sello del

CEDULA
Organo

Nombre del Organo JUZGADO CIVIL Y COMERCIAL N* 10- MAR DEL

PLATA

Domicilio del Organo Almirante Brown Nro: 1771, MAR DEL PLATA
Nombre del
Requerido MERCADO PAGO ASSET MANAGEMENT S.A.
DOMICILIO: AV, CASEROS NRO; 3039

1[o3 [26

11.00 hh LOCALIDAD/PARTIDO:
PISO DTO. UNIDAD CIUDAD AUTONOMA DE

BUENOS AIRES

TIPO DE DOMICILIO (Indicar por SI - NO según corresponda

Denunciado SI Constituido NO

: RECIBIDO
CARÁCTER (Indicar por SI - NO según Po e

Y/O HABILITACION DE DIA Y NO
HORA

URGENTE NO
OBSERVACIONES ESPECIALES

(Traslado de demanda - Art.94CPCC- Art.524 CPCC - Bajo responsabilidad de la
parte)

(testar lo que no corresponda)

JS CIVIL Y MAR DEL [NO
COMERCIAL | PLATA — onias
TO A A EA HA A AA
o
re Expte. NeÍZONA ÍFUERO No e DEP. JUD. es PERSONAL

NOTIFICO a Ud, que en el expediente caratulado FT
WALTER RICARDO C/ BIERNVERT CLAUDIA CARINA S/ COBRO
EJECUTIVO (Expte. N* MP - 1493- 2026)"

que tramita por ante este órgano, se ha resuelto: "Funcionario
Firmante 11/02/2026 13:01:47 - TONTO Mariana Lucia -

JUEZ - (...) 5. En atención a lo solicitado, bajo responsabilidad del
peticionante, trábese embargo sobre las sumas de dinero que tenga
el ejecutado en su cuenta de Mercado Pago (Mercado Libre SRL) hasta
cubrir las sumas supra indicadas, a cuyo fin Notifíquese. En este
sentido, aclárese que: a) de contar la demandada con una o varias
cuentas bancarias asociadas a la billetera virtual, previo a trabar el
embargo sobre esta última deberá Mercado Pago (Mercado Libre SRL)
comunicar al Juzgado los datos de las mismas a los fines de que la
medida cautelar se haga efectiva sobre las cuentas bancarias en
cuestión con orden desde este Juzgado. b) caso contrario -esto es, de
no contar con cuentas bancarias asociadas de la demandada- hágase
saber que se trabará el embargo sobre la billetera virtual siempre que
los fondos resulten ser propiedad de la ejecutada, y a tal fin, ordénese
a la oficiada que únicamente proceda al bloqueo inmediato de las
sumas embargadas, informando al Juzgado dentro de los diez días
corridos de cumplida la medida, acerca de los fondos que resulten
embargados. Cumplido dicho plazo, y de no mediar comunicación en
contrario del Juzgado, dichas sumas deberán ser depositadas en el
Banco de la provincia de Buenos Aires - Sucursal Tribunales Local, a la
orden de este Juzgado y como pertenecientes a estos actuados.

(... TONTO Mariana Lucía - JUEZ.

Copias: NO

NOTA: Por el presente se le hace saber que deberá proceder a
embargar los fondos que posea la Sra. BIERNVERT CLAUDIA
CARINA, titular del Dni 27.164.468, en el presente o futuro en la
billetera digital correspondiente a la plataforma de pagos virtuales
denominada Mercado Pago, por la suma de PESOS UN MILLÓN
TRESCIENTOS CINCUENTA MIL ($ 1.350.000). Las sumas
retenidas deberán ser depositadas en la cuenta Judicial en pesos

N* 929530/2 en la moneda : -.

solicitada, CBU 0140423827610292953026, Sucursal 6102, CUIT
Poder Judicial 30-70721665-0 del Banco de la Provincia de
Buenos Aires

Para su conocimiento a continuación se transcriben los siguientes
artículos:

ARTÍCULO 531? del Código Civil y Comercial de la Provincia de
Buenos Aires: Bienes en poder de un tercero. Si los bienes
embargados se encontraren en poder de un tercero, se notificará a

ácte an al día nareannalmanta a nar cánula En alasen dal at

736* del Código Civil, si el notificado del embargo pagase
indebidamente al deudor embargado, el juez hará efectiva su
responsabilidad en el mis

====================================================================================================
TIPO: EMBARGO
ID: 522288
NOMBRE: Embargo - usuario
CLASIFICACION: Embargo
====================================================================================================
TITZIZO, 9:95 | TEXTO Y DATOS DE LA NOTIFICACIÓN - SUPREMA CORTE DE JUSTICIA - NOTIFICACIONES ELEGTRÓNICAS
TEXTO Y DATOS DE LA NOTIFICACIÓN

BURRONI Edgar Jose - 20129293641 Qhnotificaciones.scba.gov.ar
TRIBUNAL DEL TRABAJO N* 3 - BRAGADO

— E TILIO GONZALO MATIAS C/ GIL GUSTAVO MANUEL S/ EJECUCION D
20280 | A
otififación: OFICIO RECIBIDO

20129293641 Gnotificaciones.scba.gov.ar
13/2/2026 E
10/2/2026 13:41:04
Firma válida

0.

q

Bragado 05 de febrero de 2026.-

AL HEÑOR|GERENTE
MERCADO] PAGO

Avenida pseros n” 3039, Piso 2?
Ciudad A ¡prema de Buenos Aires (C1264AKK)
AD)

Tego e " do de da: a Ud. el presente con relación a los autos caratuladp

GONZALO) MATIASC/ GIL GUSTAVO MANUEL S/ EJECUCIÓN DE CONVENIO” Expté.| NP 20280
enltrámite[ por ante el Tribunal del Trabajo n* 3 de Bragado, Departamento Judicial d cedes
(B], Secrétaría Única, a efectos de que proceda a si ha tomado razón de edida
calitelar didenada con fecha 04/09/25 en los autos del rubro, la cual ha sido recepciohada el día
28/10/25. El auto que ordenara dicha medida dice: “/Igado, en la fecha indicada en lajaofista cia
de la firma digital.- AUTOS Y VISTOS: ... Como se pide en la presentación] |de fecha
28/08/28 ||detretase embargo sobre las sumas depositadas y/o futuras a depopilarise Al
cualquierlcontepto que posea el demandado en MERCADO PAGO, figurando el mismó foma GIL
GUSTAVO (CUIT N” 23-20026643-9), con domicilio en calle Pellegrini N* 1880, de la cividad de
Bragado | Pcla de Es As. y/o con el nombre de fantasía de su comercio deno ido! “La

# Crear una plantilla de análisis manual

La idea es leer cada caso y llenar una tabla con observaciones.

In [60]:
columnas_analisis = [
    "id",
    "clasificacion",
    "nombre",
    "organismo_o_juzgado",
    "destinatario",
    "persona_principal",
    "dni_cuit_cuil",
    "expediente",
    "caratula",
    "fecha",
    "monto",
    "cuenta_cbu_cvu_alias",
    "datos_solicitados",
    "email_respuesta",
    "observaciones",
    "calidad_ocr"
]

analisis_manual = pd.DataFrame(columns=columnas_analisis)

analisis_manual

Empty DataFrame
Columns: [id, clasificacion, nombre, organismo_o_juzgado, destinatario, persona_principal, dni_cuit_cuil, expediente, caratula, fecha, monto, cuenta_cbu_cvu_alias, datos_solicitados, email_respuesta, observaciones, calidad_ocr]
Index: []

# Crear archivo de muestras para revisar más cómodo
Esto te genera archivos .txt separados para leerlos en VS Code sin perderte.

In [63]:
SAMPLES_DIR = PROCESSED_DIR / "muestras_lectura"
SAMPLES_DIR.mkdir(parents=True, exist_ok=True)

def guardar_muestras_lectura(df, tipo, cantidad=10):
    muestra = df[df["clasificacion"] == tipo].sample(n=cantidad, random_state=42)

    for _, row in muestra.iterrows():
        filename = f"{tipo.lower()}_{row['id']}.txt"
        path = SAMPLES_DIR / filename

        contenido = f"""TIPO: {tipo}
ID: {row['id']}
NOMBRE: {row['nombre']}
CLASIFICACION: {row['clasificacion']}

{'=' * 80}

{row['texto_ocr']}
"""

        with open(path, "w", encoding="utf-8") as f:
            f.write(contenido)

    print(f"Muestras guardadas para {tipo} en:", SAMPLES_DIR)

In [64]:
guardar_muestras_lectura(df_objetivo_csv, "Oficio", cantidad=10)
guardar_muestras_lectura(df_objetivo_csv, "Embargo", cantidad=10)

Muestras guardadas para Oficio en: E:\CAROLA\CAROLA TRABAJO\PASANTIA UNNE - AGENTE ASUNTOS LEGALES\pasantia-segem-agentes-ia\data\processed\muestras_lectura
Muestras guardadas para Embargo en: E:\CAROLA\CAROLA TRABAJO\PASANTIA UNNE - AGENTE ASUNTOS LEGALES\pasantia-segem-agentes-ia\data\processed\muestras_lectura

# Crear una tabla manual inicial

In [65]:
plantilla_path = PROCESSED_DIR / "plantilla_analisis_manual_oficios_embargos.csv"

analisis_manual.to_csv(plantilla_path, index=False, encoding="utf-8-sig")

print("Plantilla guardada en:", plantilla_path)

Plantilla guardada en: E:\CAROLA\CAROLA TRABAJO\PASANTIA UNNE - AGENTE ASUNTOS LEGALES\pasantia-segem-agentes-ia\data\processed\plantilla_analisis_manual_oficios_embargos.csv

# Etapa 3 - Limpieza de textos OCR

Objetivo: limpiar los textos de oficios y embargos válidos para dejarlos en un formato más usable para análisis posterior con IA.

La limpieza incluye:

- corrección básica de encoding y acentos rotos;
- limpieza preventiva de HTML con Beautiful Soup;
- normalización de espacios;
- normalización de tabulaciones;
- normalización de saltos de línea;
- reducción de ruido visual;
- conversión a Markdown;
- conservación del texto original.

In [ ]:
import sys
from pathlib import Path

# Permite importar src tanto al ejecutar desde notebooks/ como desde la raiz.
directorio_actual = Path.cwd().resolve()
if directorio_actual.name == "notebooks":
    PROJECT_ROOT = directorio_actual.parent
elif (directorio_actual / "src").exists():
    PROJECT_ROOT = directorio_actual

if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

PROCESSED_DIR = PROJECT_ROOT / "data" / "processed"

from src.cleaning import (
    convertir_a_markdown,
    guardar_muestras_markdown,
    limpiar_texto_legal,
    normalizar_para_busqueda,
)

In [ ]:
# Reconstruccion defensiva para ejecuciones parciales del notebook.
if "df_objetivo_csv" not in globals():
    columnas_requeridas = {"estado_texto_ocr", "clasificacion"}
    faltantes = columnas_requeridas.difference(df_csv.columns)
    if faltantes:
        raise KeyError(
            "No se puede reconstruir df_objetivo_csv. "
            f"Faltan columnas en df_csv: {sorted(faltantes)}"
        )

    df_objetivo_csv = df_csv[
        (df_csv["estado_texto_ocr"] == "ok")
        & (df_csv["clasificacion"].isin(["Oficio", "Embargo"]))
    ].copy()

df_limpieza = df_objetivo_csv.copy()
print("Registros a limpiar:", len(df_limpieza))

In [ ]:
# Se conserva texto_ocr y todas las columnas originales sin sobrescribirlas.
df_limpieza["largo_original"] = (
    df_limpieza["texto_ocr"].fillna("").astype(str).str.len()
)
df_limpieza["texto_limpio"] = df_limpieza["texto_ocr"].apply(
    limpiar_texto_legal
)
df_limpieza["texto_normalizado_busqueda"] = df_limpieza[
    "texto_limpio"
].apply(normalizar_para_busqueda)
df_limpieza["largo_limpio"] = df_limpieza["texto_limpio"].str.len()
df_limpieza["texto_markdown"] = df_limpieza.apply(
    convertir_a_markdown,
    axis=1,
)
df_limpieza["diferencia_largo"] = (
    df_limpieza["largo_original"] - df_limpieza["largo_limpio"]
)

df_limpieza.head()

## Comparación de calidad

In [ ]:
df_limpieza[
    ["largo_original", "largo_limpio", "diferencia_largo"]
].describe()

In [ ]:
ids_revision = [504422, 498355]
mascara_ids = df_limpieza["id"].astype(str).isin(
    [str(id_revision) for id_revision in ids_revision]
)
ejemplos_revision = df_limpieza[mascara_ids]

if len(ejemplos_revision) != len(ids_revision):
    muestras = []
    for tipo in ["Oficio", "Embargo"]:
        candidatos = df_limpieza[df_limpieza["clasificacion"] == tipo]
        if not candidatos.empty:
            muestras.append(candidatos.sample(n=1, random_state=42))
    ejemplos_revision = pd.concat(muestras) if muestras else df_limpieza.head(0)

for _, row in ejemplos_revision.iterrows():
    print("=" * 100)
    print(f"ID: {row['id']} | CLASIFICACION: {row['clasificacion']}")
    print("-" * 100)
    print("ANTES (texto_ocr):")
    print(str(row["texto_ocr"])[:4000])
    print("-" * 100)
    print("DESPUES (texto_limpio):")
    print(row["texto_limpio"][:4000])
    print()

## Guardar resultados procesados

In [ ]:
PROCESSED_DIR.mkdir(parents=True, exist_ok=True)
MARKDOWN_DIR = PROCESSED_DIR / "muestras_markdown"

guardar_muestras_markdown(
    df_limpieza,
    MARKDOWN_DIR,
    cantidad_por_tipo=5,
    random_state=42,
)

csv_limpio_path = PROCESSED_DIR / "oficios_embargos_limpios.csv"
json_limpio_path = PROCESSED_DIR / "oficios_embargos_limpios.json"

df_limpieza.to_csv(csv_limpio_path, index=False, encoding="utf-8-sig")
df_limpieza.to_json(
    json_limpio_path,
    orient="records",
    force_ascii=False,
    indent=2,
)

print("Muestras Markdown:", MARKDOWN_DIR)
print("CSV limpio:", csv_limpio_path)
print("JSON limpio:", json_limpio_path)

## Criterio de limpieza

La limpieza aplicada es **conservadora**: no convierte el texto principal a minúsculas, no elimina acentos y no intenta corregir ni descartar palabras propias del OCR que podrían contener información legal relevante.

Beautiful Soup se utiliza de manera preventiva para retirar etiquetas, scripts, estilos y entidades HTML si aparecen. La exploración inicial mostró poco HTML real; el problema principal observado fue el ruido propio del OCR.

La columna original `texto_ocr` se conserva sin modificaciones. Se agregan las columnas:

- `texto_limpio`
- `texto_normalizado_busqueda`
- `texto_markdown`
- `largo_original`
- `largo_limpio`
- `diferencia_largo`

# VERIFICACION

In [67]:
import pandas as pd
from pathlib import Path

PROJECT_ROOT = Path.cwd().parent
PROCESSED_DIR = PROJECT_ROOT / "data" / "processed"

csv_limpio_path = PROCESSED_DIR / "oficios_embargos_limpios.csv"

df_limpieza = pd.read_csv(csv_limpio_path)

print("Archivo existe:", csv_limpio_path.exists())
print("Shape df_limpieza:", df_limpieza.shape)

Archivo existe: True
Shape df_limpieza: (1055, 14)

In [68]:
columnas_esperadas = [
    "texto_ocr",
    "texto_limpio",
    "texto_normalizado_busqueda",
    "texto_markdown",
    "largo_original",
    "largo_limpio",
    "diferencia_largo"
]

for col in columnas_esperadas:
    print(col, "OK" if col in df_limpieza.columns else "FALTA")

texto_ocr OK
texto_limpio OK
texto_normalizado_busqueda OK
texto_markdown OK
largo_original OK
largo_limpio OK
diferencia_largo OK

In [69]:
print("Nulos en texto_limpio:", df_limpieza["texto_limpio"].isna().sum())
print("Vacíos en texto_limpio:", (df_limpieza["texto_limpio"].astype(str).str.strip() == "").sum())

Nulos en texto_limpio: 0
Vacíos en texto_limpio: 0

In [70]:
df_limpieza[["largo_original", "largo_limpio", "diferencia_largo"]].describe()

       largo_original   largo_limpio  diferencia_largo
count     1055.000000    1055.000000       1055.000000
mean      4631.088152    4516.222749        114.865403
std       5834.164015    5379.115874        849.441643
min         67.000000      65.000000          1.000000
25%       2598.000000    2586.000000          2.000000
50%       3586.000000    3575.000000          3.000000
75%       4649.000000    4631.000000          4.000000
max     109112.000000  105529.000000      15023.000000

In [71]:
for tipo in ["Oficio", "Embargo"]:
    row = df_limpieza[df_limpieza["clasificacion"] == tipo].sample(1, random_state=42).iloc[0]

    print("=" * 100)
    print("TIPO:", tipo)
    print("ID:", row["id"])
    print("=" * 100)

    print("\n--- ORIGINAL ---\n")
    print(row["texto_ocr"][:1500])

    print("\n--- LIMPIO ---\n")
    print(row["texto_limpio"][:1500])

    print("\n--- MARKDOWN ---\n")
    print(row["texto_markdown"][:1500])

====================================================================================================
TIPO: Oficio
ID: 546322
====================================================================================================

--- ORIGINAL ---

236
pola 13

OFICIO JUDICIAL
Buenos Aires, de marzo de 2026

MERCADOLIBRE SRL
Av. Caseros 3039, Piso 2 —- CABA.
Ss J D

Tengo el agrado de dirigirme a Ud. en mi carácter de letrado de la parte actora en el
expediente caratulado “DE LOS SANTOS, PABLO ROBERTO C/ GIMENEZ, PABLO
FABIAN Y OTROS S/DAÑOS Y PERJUICIOS(ACC.TRAN. C/LES. O MUERTE)” (Expte.
43264/2021) que tramita en el Juzgado Nacional en lo Civil N*65, sito en Inmigrantes 1950
piso 6?, CABA, a cargo de la Dra. María Gabriela FERNANDEZ ZURITA, Secretaría única a
cargo del Dr. Diego Martín DE LA IGLESIA. Se ha dispuesto a dirigir a Ud. el presente a fin
de solicitarle que informe el último domicilio registrado del señor Cairo CLAROS PATZI DNI
93.946.731.

El auto que ordena la medida dice así en su parte pertinente: “Buenos Aires, 16 de
diciembre de 2025 (...) Sin perjuicio de destacar que ya ha sido ordenada la publicación de
edictos, líbrense los oficios que se solicitan en los términos del artículo 400 del CPCCN.” Fdo.
LEONARDO BONETTI FRANCO, Sr. Prosecretario Administrativo Interino.

Se deja constancia que el presente expediente cuenta con un incidente de Beneficio
de Litigar Sin Gastos.

Art. 396 CPCCN: Los informes que se soliciten a las oficinas públicas, escribanos con
registro y entidades privadas deberán versar sobre hechos concretos, claramente
individualizados, controvertidos en el proceso. Procederán únicamente respecto de actos o
hechos que resulten de la documentación, archivo o registros contables del i

--- LIMPIO ---

236
pola 13

OFICIO JUDICIAL
Buenos Aires, de marzo de 2026

MERCADOLIBRE SRL
Av. Caseros 3039, Piso 2 —- CABA.
Ss J D

Tengo el agrado de dirigirme a Ud. en mi carácter de letrado de la parte actora en el
expediente caratulado "DE LOS SANTOS, PABLO ROBERTO C/ GIMENEZ, PABLO
FABIAN Y OTROS S/DAÑOS Y PERJUICIOS(ACC.TRAN. C/LES. O MUERTE)" (Expte.
43264/2021) que tramita en el Juzgado Nacional en lo Civil N*65, sito en Inmigrantes 1950
piso 6?, CABA, a cargo de la Dra. María Gabriela FERNANDEZ ZURITA, Secretaría única a
cargo del Dr. Diego Martín DE LA IGLESIA. Se ha dispuesto a dirigir a Ud. el presente a fin
de solicitarle que informe el último domicilio registrado del señor Cairo CLAROS PATZI DNI
93.946.731.

El auto que ordena la medida dice así en su parte pertinente: "Buenos Aires, 16 de
diciembre de 2025 (...) Sin perjuicio de destacar que ya ha sido ordenada la publicación de
edictos, líbrense los oficios que se solicitan en los términos del artículo 400 del CPCCN." Fdo.
LEONARDO BONETTI FRANCO, Sr. Prosecretario Administrativo Interino.

Se deja constancia que el presente expediente cuenta con un incidente de Beneficio
de Litigar Sin Gastos.

Art. 396 CPCCN: Los informes que se soliciten a las oficinas públicas, escribanos con
registro y entidades privadas deberán versar sobre hechos concretos, claramente
individualizados, controvertidos en el proceso. Procederán únicamente respecto de actos o
hechos que resulten de la documentación, archivo o registros contables del i

--- MARKDOWN ---

# Documento legal

## Metadatos

* ID: 546322
* Nombre: Solicitud de informacion de usuarios
* Clasificación: Oficio

## Texto limpio

236
pola 13

OFICIO JUDICIAL
Buenos Aires, de marzo de 2026

MERCADOLIBRE SRL
Av. Caseros 3039, Piso 2 —- CABA.
Ss J D

Tengo el agrado de dirigirme a Ud. en mi carácter de letrado de la parte actora en el
expediente caratulado "DE LOS SANTOS, PABLO ROBERTO C/ GIMENEZ, PABLO
FABIAN Y OTROS S/DAÑOS Y PERJUICIOS(ACC.TRAN. C/LES. O MUERTE)" (Expte.
43264/2021) que tramita en el Juzgado Nacional en lo Civil N*65, sito en Inmigrantes 1950
piso 6?, CABA, a cargo de la Dra. María Gabriela FERNANDEZ ZURITA, Secretaría única a
cargo del Dr. Diego Martín DE LA IGLESIA. Se ha dispuesto a dirigir a Ud. el presente a fin
de solicitarle que informe el último domicilio registrado del señor Cairo CLAROS PATZI DNI
93.946.731.

El auto que ordena la medida dice así en su parte pertinente: "Buenos Aires, 16 de
diciembre de 2025 (...) Sin perjuicio de destacar que ya ha sido ordenada la publicación de
edictos, líbrense los oficios que se solicitan en los términos del artículo 400 del CPCCN." Fdo.
LEONARDO BONETTI FRANCO, Sr. Prosecretario Administrativo Interino.

Se deja constancia que el presente expediente cuenta con un incidente de Beneficio
de Litigar Sin Gastos.

Art. 396 CPCCN: Los informes que se soliciten a las oficinas públicas, escribanos con
registro y entidades privadas deberán versar sobre hechos concretos, claramente
individualizados, controvertido
====================================================================================================
TIPO: Embargo
ID: 544832
====================================================================================================

--- ORIGINAL ---

OFICIO JUDICIAL

/ L/)

Buenos Aires, de Febrero/de/2026
Al Sr. Apoderado de |
“MERCADO LIBRE S.R.L.”
S / D

De mi consideración:

Tengo el agrado de dirigirme a Ud. en los autos
caratulados “CHUQUISACA, SERGIO HORACIO C/ MENUDENCIAS
S.A, Y OTROS S/ DESPIDO ", Expediente. Nro. 21903/14, que tramita
por ante el Juzgado Nacional de Primera Instancia del Trabajo Nro. 35, sito
en la calle Tte. Gral. Juan D. Perón 990 Piso 7mo. de C.A.B.A., a mi cargo,
Secretaría única a cargo del DR. MARIANO GILLETTE TORRILLA,
para informarle que se ha decretado embargo sobre bienes de la demandada
“FAENADORA ARGENTINA S.A.” CUIT 33-71237566-9 hasta cubrir la
suma de $ 31.177,68.- (en concepto de honorarios del perito contador), con
más la de $9.000.- presupuestados provisoriamente para responder a
IMÍOreSES Y COSÍAS occ

Se le hace saber que deberá retener de las sumas que tenga la embargada
depositadas en esa entidad, por cualquier concepto, presentes y /o futuros,
los montos indicados ut supra. Dichos importes deberán ser transferidos
dentro de las 48 horas de retenidos al BANCO DE LA CIUDAD DE
BUENOS AIRES, SUCURSAL TRIBUNALES, a la orden de V.S. y como
pertenecientes a estos autos, estando abierta dicha cuenta según los
siguientes datos: C.B.U. 02900759-00294149207615 - CUIT Banco Ciudad
30-99903208-3 y Clave 0006-035- -1492-0761-4 . Asimismo, dentro de los
cinco días de recepcionado el oficio deberá informar al Juzgado el resultado
de la gestión encomendada. ono

Sin otro particular lo salu

--- LIMPIO ---

OFICIO JUDICIAL

/ L/)

Buenos Aires, de Febrero/de/2026
Al Sr. Apoderado de |
"MERCADO LIBRE S.R.L."
S / D

De mi consideración:

Tengo el agrado de dirigirme a Ud. en los autos
caratulados "CHUQUISACA, SERGIO HORACIO C/ MENUDENCIAS
S.A, Y OTROS S/ DESPIDO ", Expediente. Nro. 21903/14, que tramita
por ante el Juzgado Nacional de Primera Instancia del Trabajo Nro. 35, sito
en la calle Tte. Gral. Juan D. Perón 990 Piso 7mo. de C.A.B.A., a mi cargo,
Secretaría única a cargo del DR. MARIANO GILLETTE TORRILLA,
para informarle que se ha decretado embargo sobre bienes de la demandada
"FAENADORA ARGENTINA S.A." CUIT 33-71237566-9 hasta cubrir la
suma de $ 31.177,68.- (en concepto de honorarios del perito contador), con
más la de $9.000.- presupuestados provisoriamente para responder a
IMÍOreSES Y COSÍAS occ

Se le hace saber que deberá retener de las sumas que tenga la embargada
depositadas en esa entidad, por cualquier concepto, presentes y /o futuros,
los montos indicados ut supra. Dichos importes deberán ser transferidos
dentro de las 48 horas de retenidos al BANCO DE LA CIUDAD DE
BUENOS AIRES, SUCURSAL TRIBUNALES, a la orden de V.S. y como
pertenecientes a estos autos, estando abierta dicha cuenta según los
siguientes datos: C.B.U. 02900759-00294149207615 - CUIT Banco Ciudad
30-99903208-3 y Clave 0006-035- -1492-0761-4 . Asimismo, dentro de los
cinco días de recepcionado el oficio deberá informar al Juzgado el resultado
de la gestión encomendada. ono

Sin otro particular lo salu

--- MARKDOWN ---

# Documento legal

## Metadatos

* ID: 544832
* Nombre: Embargo - usuario
* Clasificación: Embargo

## Texto limpio

OFICIO JUDICIAL

/ L/)

Buenos Aires, de Febrero/de/2026
Al Sr. Apoderado de |
"MERCADO LIBRE S.R.L."
S / D

De mi consideración:

Tengo el agrado de dirigirme a Ud. en los autos
caratulados "CHUQUISACA, SERGIO HORACIO C/ MENUDENCIAS
S.A, Y OTROS S/ DESPIDO ", Expediente. Nro. 21903/14, que tramita
por ante el Juzgado Nacional de Primera Instancia del Trabajo Nro. 35, sito
en la calle Tte. Gral. Juan D. Perón 990 Piso 7mo. de C.A.B.A., a mi cargo,
Secretaría única a cargo del DR. MARIANO GILLETTE TORRILLA,
para informarle que se ha decretado embargo sobre bienes de la demandada
"FAENADORA ARGENTINA S.A." CUIT 33-71237566-9 hasta cubrir la
suma de $ 31.177,68.- (en concepto de honorarios del perito contador), con
más la de $9.000.- presupuestados provisoriamente para responder a
IMÍOreSES Y COSÍAS occ

Se le hace saber que deberá retener de las sumas que tenga la embargada
depositadas en esa entidad, por cualquier concepto, presentes y /o futuros,
los montos indicados ut supra. Dichos importes deberán ser transferidos
dentro de las 48 horas de retenidos al BANCO DE LA CIUDAD DE
BUENOS AIRES, SUCURSAL TRIBUNALES, a la orden de V.S. y como
pertenecientes a estos autos, estando abierta dicha cuenta según los
siguientes datos: C.B.U. 02900759-00294149207615 - CUIT Banco Ciudad
30-99903208-3 y Clave 0006-035- -1492-0761-4 . Asimismo, dentro de los
cinco días de recep

## Conclusión de la transformación a Markdown

La etapa de limpieza procesó 1055 documentos válidos clasificados como `Oficio` o `Embargo`.

La limpieza fue conservadora: se mantuvo el contenido legal original lo más intacto posible, evitando transformaciones agresivas como pasar todo a minúsculas, eliminar acentos o corregir automáticamente errores OCR.

La columna `texto_ocr` se conservó como fuente original, mientras que se generaron versiones auxiliares:

- `texto_limpio`: texto normalizado y más legible.
- `texto_normalizado_busqueda`: versión auxiliar para búsquedas.
- `texto_markdown`: versión estructurada para uso posterior con modelos de IA.

La conversión a Markdown permite separar metadatos del contenido legal y deja cada documento en un formato más claro para tareas futuras de extracción de entidades, comparación entre oficio/respuesta y revisión automática.

La validación mostró que no hay textos limpios nulos ni vacíos. La mayoría de los documentos tuvo una diferencia mínima entre el largo original y el largo limpio, lo que indica que la limpieza no fue destructiva.

# Etapa 4 - Separaci?n del dataset de embargos

En esta etapa se separa el dataset de embargos para trabajar espec?ficamente con esos documentos en an?lisis posteriores. Se parte de la base limpia `oficios_embargos_limpios.csv`, se filtran ?nicamente los registros con `clasificacion == "Embargo"` y se guarda un nuevo archivo sin modificar la base limpia original.

In [1]:
from pathlib import Path
import pandas as pd

directorio_actual = Path.cwd().resolve()
if directorio_actual.name == "notebooks":
    PROJECT_ROOT = directorio_actual.parent
elif (directorio_actual / "data" / "processed").exists():
    PROJECT_ROOT = directorio_actual
else:
    PROJECT_ROOT = directorio_actual.parent

PROCESSED_DIR = PROJECT_ROOT / "data" / "processed"

archivo_limpio = PROCESSED_DIR / "oficios_embargos_limpios.csv"
archivo_embargos = PROCESSED_DIR / "embargos_limpios.csv"

df_limpio = pd.read_csv(archivo_limpio)

if "clasificacion" not in df_limpio.columns:
    raise ValueError("No existe la columna 'clasificacion' en el archivo limpio.")

df_embargos = df_limpio[df_limpio["clasificacion"] == "Embargo"].copy()

df_embargos.to_csv(archivo_embargos, index=False, encoding="utf-8-sig")

print("Archivo de embargos guardado en:", archivo_embargos)
print("Existe archivo:", archivo_embargos.exists())
print("Cantidad de embargos:", df_embargos.shape[0])
print(df_embargos["clasificacion"].value_counts())

Archivo de embargos guardado en: E:\CAROLA\CAROLA TRABAJO\PASANTIA UNNE - AGENTE ASUNTOS LEGALES\pasantia-segem-agentes-ia\data\processed\embargos_limpios.csv
Existe archivo: True
Cantidad de embargos: 627
clasificacion
Embargo    627
Name: count, dtype: int64