**Bloque 1 — instalar GLiNER**

In [2]:
!pip install gliner pandas tqdm

Collecting gliner
  Downloading gliner-0.2.27-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (4.67.3)
Requirement already satisfied: torch>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from gliner) (2.11.0+cpu)
Collecting transformers<5.7.0,>=4.51.3 (from gliner)
  Downloading transformers-5.6.2-py3-none-any.whl.metadata (33 kB)
Requirement already satisfied: huggingface_hub>=0.21.4 in /usr/local/lib/python3.12/dist-packages (from gliner) (1.18.0)
Collecting onnxruntime (from gliner)
  Downloading onnxruntime-1.27.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (5.4 kB)
Requirement already satisfied: sentencepiece in /usr/local/lib/python3.12/dist-packages (from gliner) (0.2.1)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.2)
Requirement already satisfied: click>=8.4.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.4->gliner) (8.4.1)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.4->gliner) (3.29.2)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.4->gliner) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.4->gliner) (1.5.1)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.4->gliner) (0.28.1)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.4->gliner) (26.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.4->gliner) (6.0.3)
Requirement already satisfied: typer<0.26.0,>=0.20.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.4->gliner) (0.25.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.4->gliner) (4.15.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->gliner) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->gliner) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->gliner) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->gliner) (3.1.6)
Requirement already satisfied: regex>=2025.10.22 in /usr/local/lib/python3.12/dist-packages (from transformers<5.7.0,>=4.51.3->gliner) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers<5.7.0,>=4.51.3->gliner) (0.22.2)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers<5.7.0,>=4.51.3->gliner) (0.8.0)
Requirement already satisfied: flatbuffers in /usr/local/lib/python3.12/dist-packages (from onnxruntime->gliner) (25.12.19)
Requirement already satisfied: protobuf>=4.25.8 in /usr/local/lib/python3.12/dist-packages (from onnxruntime->gliner) (5.29.6)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.21.4->gliner) (4.13.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.21.4->gliner) (2026.5.20)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.21.4->gliner) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.21.4->gliner) (3.18)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface_hub>=0.21.4->gliner) (0.16.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=2.0.0->gliner) (1.3.0)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer<0.26.0,>=0.20.0->huggingface_hub>=0.21.4->gliner) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in /usr/local/lib/python3.12/dist-packages (from typer<0.26.0,>=0.20.0->huggingface_hub>=0.21.4->gliner) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer<0.26.0,>=0.20.0->huggingface_hub>=0.21.4->gliner) (0.0.4)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=2.0.0->gliner) (3.0.3)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer<0.26.0,>=0.20.0->huggingface_hub>=0.21.4->gliner) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer<0.26.0,>=0.20.0->huggingface_hub>=0.21.4->gliner) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer<0.26.0,>=0.20.0->huggingface_hub>=0.21.4->gliner) (0.1.2)
Downloading gliner-0.2.27-py3-none-any.whl (207 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.8/207.8 kB 6.8 MB/s eta 0:00:00
Downloading transformers-5.6.2-py3-none-any.whl (10.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.4/10.4 MB 81.2 MB/s eta 0:00:00
Downloading onnxruntime-1.27.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (18.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.7/18.7 MB 64.0 MB/s eta 0:00:00
Installing collected packages: onnxruntime, transformers, gliner
  Attempting uninstall: transformers
    Found existing installation: transformers 5.10.2
    Uninstalling transformers-5.10.2:
      Successfully uninstalled transformers-5.10.2
Successfully installed gliner-0.2.27 onnxruntime-1.27.0 transformers-5.6.2

**Bloque 2 — imports**

In [4]:
import pandas as pd
from tqdm import tqdm
from gliner import GLiNER

tqdm.pandas()

**Bloque 3 — subir archivo de embargos**

In [5]:
from google.colab import files

uploaded = files.upload()

Saving embargos_limpios.csv to embargos_limpios.csv

**Bloque 4 — cargar dataset**

In [6]:
df_embargos = pd.read_csv("embargos_limpios.csv")

print("Shape:", df_embargos.shape)
df_embargos.head()

Shape: (627, 14)

,id,texto_ocr,nombre,clasificacion,tiene_html_detectado,patrones_html_detectados,estado_texto_ocr,largo_texto_ocr,largo_original,texto_limpio,texto_normalizado_busqueda,largo_limpio,texto_markdown,diferencia_largo
0,494145,ii\n4373-350\no.gestona.profesionalU gmail.com...,Embargo - usuario,Embargo,False,[],ok,3539,3541,ii\n4373-350\no.gestona.profesionalU gmail.com...,ii 4373-350 o.gestona.profesionalu gmail.com a...,3539,# Documento legal\n\n## Metadatos\n\n* ID: 494...,2
1,494146,R\n\n012 E\n\nercado Poder Judicial de la Naci...,Embargo - usuario,Embargo,False,[],ok,3124,3125,R\n\n012 E\n\nercado Poder Judicial de la Naci...,r 012 e ercado poder judicial de la nacion juz...,3124,# Documento legal\n\n## Metadatos\n\n* ID: 494...,1
2,494147,|\nTEXTO Y PATOS DE LA NOTIFICACIÓN LE!\n\nUsu...,Embargo - usuario,Embargo,False,[],ok,5167,5169,|\nTEXTO Y PATOS DE LA NOTIFICACIÓN LE!\n\nUsu...,| texto y patos de la notificacion le! usuario...,5166,# Documento legal\n\n## Metadatos\n\n* ID: 494...,3
3,494150,02lNE\n\nOFICIO e y |\n\nCiudad Autónoma de Bu...,Embargo - usuario,Embargo,False,[],ok,3819,3820,02lNE\n\nOFICIO e y |\n\nCiudad Autónoma de Bu...,02lne oficio e y | ciudad autonoma de buenos a...,3818,# Documento legal\n\n## Metadatos\n\n* ID: 494...,2
4,494151,SDE LA NOTIFICACIÓN (\nFRAPPA LETICIA MABEL - ...,Embargo - usuario,Embargo,False,[],ok,8876,8878,SDE LA NOTIFICACIÓN (\nFRAPPA LETICIA MABEL - ...,sde la notificacion ( frappa leticia mabel - 2...,8875,# Documento legal\n\n## Metadatos\n\n* ID: 494...,3

Validación:

In [5]:
df_embargos["clasificacion"].value_counts()

clasificacion
Embargo    627
Name: count, dtype: int64

**6. Cargar GLiNER**  
Usamos el modelo que aparece en el Colab de guia

In [6]:
model = GLiNER.from_pretrained("urchade/gliner_multi_pii-v1")

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_validators.py:189: UserWarning: The `resume_download` argument is deprecated and ignored in `snapshot_download`. Downloads always resume whenever possible.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:112: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

Downloading (incomplete total...): 0.00B [00:00, ?B/s]

Fetching 4 files:   0%|          | 0/4 [00:00<?, ?it/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config.json:   0%|          | 0.00/579 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/52.0 [00:00<?, ?B/s]

spm.model:   0%|          | 0.00/4.31M [00:00<?, ?B/s]

**7. Contar tokens con el tokenizer de GLiNER**  

Primero intentamos acceder al tokenizer interno:

In [7]:
tokenizer = model.data_processor.transformer_tokenizer

Definimos funcion

In [8]:
def contar_tokens_gliner(texto):
    if pd.isna(texto):
        return 0

    texto = str(texto)

    tokens = tokenizer(
        texto,
        add_special_tokens=True,
        truncation=False
    )

    return len(tokens["input_ids"])

Ahora aplicamos sobre el texto limpio:

In [9]:
df_embargos["gliner_tokens"] = df_embargos["texto_limpio"].progress_apply(contar_tokens_gliner)

100%|██████████| 627/627 [00:02<00:00, 239.91it/s]

**8. Sacar media, mínimo y máximo**

In [10]:
df_embargos["gliner_tokens"].describe()

count     627.000000
mean     1128.094099
std       513.130490
min       149.000000
25%       771.500000
50%      1055.000000
75%      1378.000000
max      3517.000000
Name: gliner_tokens, dtype: float64

También podés sacar solo lo pedido:

In [11]:
resumen_tokens_embargos = df_embargos["gliner_tokens"].agg(["count", "mean", "min", "max"])

resumen_tokens_embargos

count     627.000000
mean     1128.094099
min       149.000000
max      3517.000000
Name: gliner_tokens, dtype: float64

En formato mas claro:

In [12]:
print("Cantidad de embargos:", df_embargos.shape[0])
print("Media de tokens:", round(df_embargos["gliner_tokens"].mean(), 2))
print("Mínimo de tokens:", df_embargos["gliner_tokens"].min())
print("Máximo de tokens:", df_embargos["gliner_tokens"].max())

Cantidad de embargos: 627
Media de tokens: 1128.09
Mínimo de tokens: 149
Máximo de tokens: 3517

**9. Explorar tokens por subtipo de embargo**  

Tu archivo tiene columna nombre, por ejemplo:

Agrupar por nombre.

Esto sirve para la tarea:

exploración de tipo de datos para ver cuántos tokens consumen

En tu caso sería: qué subtipo de embargo consume más tokens.

In [13]:
df_embargos.groupby("nombre")["gliner_tokens"].agg(["count", "mean", "min", "max"]).sort_values("mean", ascending=False)

                    count         mean  min   max
nombre
Embargo - Empleado      4  1754.750000  836  2376
Embargo - usuario     623  1124.070626  149  3517

**10. Ver embargos más largos**

In [14]:
df_embargos.sort_values("gliner_tokens", ascending=False)[
    ["id", "nombre", "clasificacion", "gliner_tokens", "largo_limpio"]
].head(20)

         id              nombre clasificacion  gliner_tokens  largo_limpio
35   496830   Embargo - usuario       Embargo           3517         10926
475  538037   Embargo - usuario       Embargo           3166          9437
4    494151   Embargo - usuario       Embargo           3050          8875
168  514558   Embargo - usuario       Embargo           3042          9372
150  513537   Embargo - usuario       Embargo           2971          8140
66   502593   Embargo - usuario       Embargo           2917          9085
394  531053   Embargo - usuario       Embargo           2762          8751
368  529783   Embargo - usuario       Embargo           2726          8689
235  522288   Embargo - usuario       Embargo           2655          7517
396  531070   Embargo - usuario       Embargo           2648          8398
570  544803   Embargo - usuario       Embargo           2565          8080
488  538090   Embargo - usuario       Embargo           2543          6956
481  538063   Embargo - usuario       Embargo           2502          8206
313  525055   Embargo - usuario       Embargo           2492          7243
486  538082   Embargo - usuario       Embargo           2410          7552
395  531066  Embargo - Empleado       Embargo           2376          6967
305  525027   Embargo - usuario       Embargo           2356          7081
267  524015   Embargo - usuario       Embargo           2338          6627
294  524091   Embargo - usuario       Embargo           2318          7375
480  538062   Embargo - usuario       Embargo           2256          6892

Y revisar uno:
Esto te ayuda a detectar si hay documentos demasiado largos para GLiNER.

In [15]:
id_largo = df_embargos.sort_values("gliner_tokens", ascending=False).iloc[0]["id"]

row = df_embargos[df_embargos["id"] == id_largo].iloc[0]

print("ID:", row["id"])
print("Tokens:", row["gliner_tokens"])
print("Nombre:", row["nombre"])

print(row["texto_limpio"][:4000])

ID: 496830
Tokens: 3517
Nombre: Embargo - usuario
UPREMA DE JUSTICIA Fecha Impresión
| 26/12/2025 - 08:53:52

1125. | A ecoroasrass MN TAR

DEN 0

| JEICIO CASILLERO VIRTUAL CON FIRMA DIGITAL

ito: [2/12/2025 00:00
bsitada en el/los domicilio/s digitales:
SARMIENTO, JULIO ISAAC-ACTOR

PODER JUDICIAL DE TUCUMÁN

LL

H106038878557

¡AL CAPITAL ES mercado
> libre

Stión Asociada en Documentos y Locaciones N* 3

"lf375/25 0 8 ENE 2026

UAM RECEPCION

Jutgalib Civillen Documentos y Locaciones 1H

San 1
|
AL SR,

Ss

S/D

JUICI
7375/23.

En los
Locadi
Coordi
Fradejas, Dr

e Tucumán, 11 de diciembre de 2025.

LITADO DE

PAGO (MERCADO LIBRE SRL)

ARMIENTO JULIO ISAAC e/ EL MALIK S.A.S. s/ COBRO EJECUTIVO - Expte. n?

del rubro que se tramitan por ante esta Oficina de Gestión Asociada en Documentos y
* 3, del Centro Judicial Capital, a cargo del Director. Dr. Hector Bazán Perez,
as, Dr. Jose Manuel Torrego, Dr. Fernando Jose Lucas Filgueira, Dra. Elena Carolina
Diego Martin Gonzalez, se ha dispuesto librar el presente oficio a los fines de que se
lar cumplimiento con la providencia que a continuación se transcribe: San Miguel de

de diciembre de 2025.- AUTOS Y VISTOS: ... CONSIDERANDO: ... RESUELVO: ... 6)

VIBARGO, de forma sucesiva, sobre fondos y/o créditos de titularidad de la demandada
$.A.S., C.U.I.T. N*30-71843097-2, -salvo cuentas sueldo- y/o plazo fijo que tenga

llb a depositar la parte demandada, hasta cubrir la suma de PESOS TREINTA Y TRES
QUINIENTOS MIL ($33.500.000) por capital, con más la suma de PESOS DIEZ

BINCUENTA MIL ($10.050.000.-) para responder -provisoriamente- por acrecidas, que posea

Mas virtuales (CVU), incluyendo especialmente billeteras digitales administradas por

de Servicios de Paga inscriptos ante el BCRA, tales como MERCADO PAGO (Mercado
UALÁ (ALAU TECNOLOGÍA S.A.U.), BRUBANK (BRUBANK S.A.U.), PREX, MODO,
PAY (MICRO SISTEMAS S.A.U.) y NARANJA X (NARANJA DIGITAL COMPAÑIA
A S/A.U.).- Para su cumplimiento, líbrese oficio de forma sucesiva, a cada entidad,

án el caso de que el destinatario del embargo tuviere medidas cautelares trabadas con

lanterioridad al presente oficio, quedará pendiente el embargo de marras y se deberá hacer efectivo
[al vencimiento de dichas medidas, debiendo comunicarse cuando se produzcan los depósitos. ...
¡HÁGASE SABER. DR. CARLOS RAÚL RIVAS - JUEZ. 7376/25 - wIG

¡SALUDO A UD. ATTE.

¡OFICIO DEPOSITADO EN CASILLERO DIGITAL: 20143876404

[Actuación firmada en fecha 11/12/2025

[Certificado digital:
[CN=FILGUEIRA Fernando José Lucas, C=AR, SERIALNUMBER=CUIL 23220578119
1]

[La autenticidad e integridad del texto puede ser comprobada en el sítio oficial del Poder Judicial de Tucumán hitps://www.justucuman.gov,ar,

Carátula; $

Unidad Jl
Tipo'Act

Fecha Depósi
Notifica
201438764
zona -

201438
335396

5159 -

|
ACTUACIONES N* (75/25 IAS

A : 08 EtIE 2026

MM

H106038875678

6404 - TA

JPREMA E u Fecha Impresión
26/12/2025 - 08:52:47

PS
TO| JULIO ISAAC C/ EL MALIK S.A.S. S/ COBRO EJECUTIVO

ICINA DE GESTIÓN ASOCIADA EN DOCUMENTOS Y LOCACIONES N? 3

ción: SENTENCIA MONITORIA EJECUTIVA
: (p/12/2025 -00:00

Asitada en el/los domicilio/s digital/es:

IRMIENTO, JULIO ISAAC-ACTOR

| MALIK S.A.S. , DEMANDADO

h RBELL, EDUARDO MIGUEL-POR DERECHO PROPIO
AJA DE PREVISION Y S.S. ABOGADOS Y PROC. -

SO PA
¿2 MONta

Caja)
>

RECEPCION

en Documentos y Locaciones UI" Nominación

Juzgadd Civi
| |

JUICIO: SARMIENTO JULIO ISAAC c/ EL MALIK S.A.S. s/ COBRO EJECUTIVO - EXPTE. N*
7375/25
San Miguel de Tucumán, 11 de diciembre de 2025.-
AUTOS Y VISTOS:
Para resolve] estos autos caratulados "SARMIENTO JULIO ISAAC c/ EL MALIK S.A.S. s/ COBRO
EJECU IVO! y;
CONSIDERANDO:

|
Que la partelactora, JULIO ISAAC SARMIENTO, D.N.I. N? 23.116.680, a través de su letrado apoderado
cupos MIGUEL TARBELL, inicia acción ejecutiva monitoria en contra de EL MALIK S.A.S. ,
C.U.LT. N230171843097-2, con domicilio en Calle Maipú N?* 1393, San Miguel de Tucumán, por la suma

de PESOS T.
con m ás inte
|
Los qué, sob

1- che ue,

ba > 025...

2- cheque,
28/07/2025.-

REINTA

**11. Labels iniciales para embargos**

Para empezar con GLiNER, yo usaría labels específicos de embargos:

In [16]:
labels_embargo = [
    "persona embargada",
    "empresa embargada",
    "DNI",
    "CUIT",
    "CUIL",
    "monto",
    "monto embargado",
    "monto costas",
    "CBU",
    "CVU",
    "cuenta judicial",
    "banco",
    "juzgado",
    "expediente",
    "caratula",
    "fecha",
    "email",
    "destinatario",
    "plazo"
]

**12. Probar GLiNER con un embargo**

In [17]:
row = df_embargos.sample(1, random_state=42).iloc[0]

text = row["texto_limpio"]

entities = model.predict_entities(text, labels_embargo)

print("ID:", row["id"])
print("Tokens:", row["gliner_tokens"])

for entity in entities:
    print(entity["text"], "=>", entity["label"], "| score:", round(entity.get("score", 0), 3))

ID: 544832
Tokens: 562
Expediente. Nro. 21903/14 => expediente | score: 0.861
Juzgado Nacional de Primera Instancia del Trabajo Nro. 35 => juzgado | score: 0.927
FAENADORA ARGENTINA S.A. => empresa embargada | score: 0.93
33-71237566-9 => CUIT | score: 0.885
$ 31.177,68.- => monto | score: 0.759
$9.000.- => monto | score: 0.741
IMÍOreSES Y COSÍAS => monto costas | score: 0.519
BANCO DE LA CIUDAD DE
BUENOS AIRES => banco | score: 0.936
30-99903208-3 => CUIT | score: 0.527

**13. Guardar entidades en formato tabla**

Después de probar uno o dos, podés probar con 10:

In [18]:
def extraer_entidades_documento(row, labels):
    text = str(row["texto_limpio"])

    try:
        entities = model.predict_entities(text, labels)

        resultados = []

        for ent in entities:
            resultados.append({
                "id": row["id"],
                "nombre": row["nombre"],
                "clasificacion": row["clasificacion"],
                "gliner_tokens": row["gliner_tokens"],
                "entidad_texto": ent.get("text"),
                "entidad_label": ent.get("label"),
                "score": ent.get("score")
            })

        return resultados

    except Exception as e:
        return [{
            "id": row["id"],
            "nombre": row["nombre"],
            "clasificacion": row["clasificacion"],
            "gliner_tokens": row["gliner_tokens"],
            "entidad_texto": None,
            "entidad_label": "ERROR",
            "score": None,
            "error": str(e)
        }]

Aplicar a muestra:

In [19]:
muestra_embargos = df_embargos.sample(10, random_state=42)

todos_resultados = []

for _, row in tqdm(muestra_embargos.iterrows(), total=len(muestra_embargos)):
    todos_resultados.extend(extraer_entidades_documento(row, labels_embargo))

df_entidades_embargos_muestra = pd.DataFrame(todos_resultados)

df_entidades_embargos_muestra.head(50)

 10%|█         | 1/10 [00:05<00:51,  5.77s/it]/usr/local/lib/python3.12/dist-packages/gliner/data_processing/processor.py:417: UserWarning: Sentence of length 997 has been truncated to 384
  batch = [self.preprocess_example(b["tokenized_text"], b[key], class_to_ids) for b in batch_list]
 20%|██        | 2/10 [00:11<00:45,  5.67s/it]/usr/local/lib/python3.12/dist-packages/gliner/data_processing/processor.py:417: UserWarning: Sentence of length 987 has been truncated to 384
  batch = [self.preprocess_example(b["tokenized_text"], b[key], class_to_ids) for b in batch_list]
 30%|███       | 3/10 [00:17<00:41,  5.99s/it]/usr/local/lib/python3.12/dist-packages/gliner/data_processing/processor.py:417: UserWarning: Sentence of length 738 has been truncated to 384
  batch = [self.preprocess_example(b["tokenized_text"], b[key], class_to_ids) for b in batch_list]
 40%|████      | 4/10 [00:22<00:32,  5.37s/it]/usr/local/lib/python3.12/dist-packages/gliner/data_processing/processor.py:417: UserWarning: Sentence of length 1121 has been truncated to 384
  batch = [self.preprocess_example(b["tokenized_text"], b[key], class_to_ids) for b in batch_list]
 50%|█████     | 5/10 [00:28<00:27,  5.55s/it]/usr/local/lib/python3.12/dist-packages/gliner/data_processing/processor.py:417: UserWarning: Sentence of length 1774 has been truncated to 384
  batch = [self.preprocess_example(b["tokenized_text"], b[key], class_to_ids) for b in batch_list]
 60%|██████    | 6/10 [00:33<00:21,  5.44s/it]/usr/local/lib/python3.12/dist-packages/gliner/data_processing/processor.py:417: UserWarning: Sentence of length 1246 has been truncated to 384
  batch = [self.preprocess_example(b["tokenized_text"], b[key], class_to_ids) for b in batch_list]
 70%|███████   | 7/10 [00:38<00:15,  5.31s/it]/usr/local/lib/python3.12/dist-packages/gliner/data_processing/processor.py:417: UserWarning: Sentence of length 723 has been truncated to 384
  batch = [self.preprocess_example(b["tokenized_text"], b[key], class_to_ids) for b in batch_list]
 80%|████████  | 8/10 [00:43<00:10,  5.41s/it]/usr/local/lib/python3.12/dist-packages/gliner/data_processing/processor.py:417: UserWarning: Sentence of length 468 has been truncated to 384
  batch = [self.preprocess_example(b["tokenized_text"], b[key], class_to_ids) for b in batch_list]
 90%|█████████ | 9/10 [00:48<00:05,  5.17s/it]/usr/local/lib/python3.12/dist-packages/gliner/data_processing/processor.py:417: UserWarning: Sentence of length 875 has been truncated to 384
  batch = [self.preprocess_example(b["tokenized_text"], b[key], class_to_ids) for b in batch_list]
100%|██████████| 10/10 [00:53<00:00,  5.39s/it]

,id,nombre,clasificacion,gliner_tokens,entidad_texto,entidad_label,score
0,544832,Embargo - usuario,Embargo,562,Expediente. Nro. 21903/14,expediente,0.861329
1,544832,Embargo - usuario,Embargo,562,Juzgado Nacional de Primera Instancia del Trab...,juzgado,0.927369
2,544832,Embargo - usuario,Embargo,562,FAENADORA ARGENTINA S.A.,empresa embargada,0.929711
3,544832,Embargo - usuario,Embargo,562,33-71237566-9,CUIT,0.884942
4,544832,Embargo - usuario,Embargo,562,"$ 31.177,68.-",monto,0.758830
5,544832,Embargo - usuario,Embargo,562,$9.000.-,monto,0.740670
6,544832,Embargo - usuario,Embargo,562,IMÍOreSES Y COSÍAS,monto costas,0.518556
7,544832,Embargo - usuario,Embargo,562,BANCO DE LA CIUDAD DE\nBUENOS AIRES,banco,0.935519
8,544832,Embargo - usuario,Embargo,562,30-99903208-3,CUIT,0.527177
9,546230,Embargo - usuario,Embargo,1542,JUZGADO CIVIL 7,juzgado,0.590764
10,546230,Embargo - usuario,Embargo,1542,40471/2023,expediente,0.544367
11,546230,Embargo - usuario,Embargo,1542,expte n* 40471/2023,expediente,0.720688
12,546230,Embargo - usuario,Embargo,1542,Juzgado Nacional de Primera Instancia en lo Ci...,juzgado,0.803238
13,546230,Embargo - usuario,Embargo,1542,jncivil7Opjn.gov.ar,email,0.993556
14,546230,Embargo - usuario,Embargo,1542,PESOS UN MILLON QUINIENTOS MIL,monto,0.570013
15,546230,Embargo - usuario,Embargo,1542,$1.500.000,monto,0.656647
16,546230,Embargo - usuario,Embargo,1542,"Banco\nde la Nación Argentina, Sucursal Tribun...",banco,0.945156
17,546230,Embargo - usuario,Embargo,1542,0110025950099897445578,CBU,0.983295
18,546230,Embargo - usuario,Embargo,1542,3 de diciembre de 2025,fecha,0.687914
19,543050,Embargo - usuario,Embargo,1470,JUZGADO DE FAMILIA N? 5 - SAN ISIDRO,juzgado,0.892531
20,543050,Embargo - usuario,Embargo,1470,20261011930Qnotificaciones.scba.gov.ar,destinatario,0.815372
21,543050,Embargo - usuario,Embargo,1470,13/3/2026,fecha,0.846929
22,543050,Embargo - usuario,Embargo,1470,Expte: SI - 38561 - 2022,expediente,0.682495
23,543050,Embargo - usuario,Embargo,1470,"Juzgado de Familia N* 5, Departamento Judicial...",juzgado,0.631902
24,543050,Embargo - usuario,Embargo,1470,juzfam5-siOjusbuenosaires.gov.ar,email,0.507267
25,543050,Embargo - usuario,Embargo,1470,0000003100087743731453,CVU,0.783683
26,543050,Embargo - usuario,Embargo,1470,$14.309.175,monto,0.800859
27,543050,Embargo - usuario,Embargo,1470,PESOS CATORCE MILLONES TRESCIENTOS NUEVE MIL C...,monto,0.549221
28,543050,Embargo - usuario,Embargo,1470,$7.200.000,monto,0.795342
29,543050,Embargo - usuario,Embargo,1470,PESOS SIETE MILLONES DOCIENTOS MIL,monto,0.588330
30,518820,Embargo - usuario,Embargo,1081,REZZET MA CIELO C/ GIECO ORLANDO MN,caratula,0.886669
31,518820,Embargo - usuario,Embargo,1081,Expte. N* 5013,expediente,0.882836
32,518820,Embargo - usuario,Embargo,1081,Tribunales,juzgado,0.712265
33,518820,Embargo - usuario,Embargo,1081,Cuenta N* 62-208\n0894723,cuenta judicial,0.771211
34,518820,Embargo - usuario,Embargo,1081,"04.11.2024, 09:32 hs.",fecha,0.844658
35,518820,Embargo - usuario,Embargo,1081,Orlando Jesús,persona embargada,0.591822
36,518820,Embargo - usuario,Embargo,1081,30-70308853-4,CUIT,0.592588
37,538081,Embargo - usuario,Embargo,1746,MERCADO PAGO ASSET MANAGEMENT S.A.,destinatario,0.883410
38,538081,Embargo - usuario,Embargo,1746,JUZGADO CIVIL Y COMERCIAL N* 10- MAR DEL\n\nPLATA,juzgado,0.841967
39,538081,Embargo - usuario,Embargo,1746,MERCADO PAGO ASSET MANAGEMENT S.A.,destinatario,0.889689
40,538081,Embargo - usuario,Embargo,1746,Expte. N* MP - 1493- 2026,expediente,0.762089
41,538081,Embargo - usuario,Embargo,1746,11/02/2026 13:01:47,fecha,0.760238
42,538081,Embargo - usuario,Embargo,1746,Mercado Libre SRL,destinatario,0.501680
43,522288,Embargo - usuario,Embargo,2655,20129293641,CUIT,0.561078
44,522288,Embargo - usuario,Embargo,2655,Expté.| NP 20280,expediente,0.824253
45,522288,Embargo - usuario,Embargo,2655,"Departamento Judicial d cedes\n(B], Secrétaría...",juzgado,0.865774
46,522288,Embargo - usuario,Embargo,2655,04/09/25,fecha,0.847663
47,522288,Embargo - usuario,Embargo,2655,28/10/25,fecha,0.668659
48,522288,Embargo - usuario,Embargo,2655,23-20026643-9,CUIT,0.650849
49,536721,Embargo - usuario,Embargo,1835,JUZGADO EN LO CIVIL Y COMERCIAL N? 4 - SAN NIC...,juzgado,0.854395

Guardar:

In [20]:
df_entidades_embargos_muestra.to_csv("entidades_embargos_muestra_gliner.csv", index=False, encoding="utf-8-sig")

Descargar:

In [21]:
files.download("entidades_embargos_muestra_gliner.csv")

Resultado

In [22]:
df_embargos.shape
df_embargos["gliner_tokens"].describe()
df_embargos.sort_values("gliner_tokens", ascending=False)[["id", "nombre", "gliner_tokens"]].head(10)
df_entidades_embargos_muestra.head(50)

,id,nombre,clasificacion,gliner_tokens,entidad_texto,entidad_label,score
0,544832,Embargo - usuario,Embargo,562,Expediente. Nro. 21903/14,expediente,0.861329
1,544832,Embargo - usuario,Embargo,562,Juzgado Nacional de Primera Instancia del Trab...,juzgado,0.927369
2,544832,Embargo - usuario,Embargo,562,FAENADORA ARGENTINA S.A.,empresa embargada,0.929711
3,544832,Embargo - usuario,Embargo,562,33-71237566-9,CUIT,0.884942
4,544832,Embargo - usuario,Embargo,562,"$ 31.177,68.-",monto,0.758830
5,544832,Embargo - usuario,Embargo,562,$9.000.-,monto,0.740670
6,544832,Embargo - usuario,Embargo,562,IMÍOreSES Y COSÍAS,monto costas,0.518556
7,544832,Embargo - usuario,Embargo,562,BANCO DE LA CIUDAD DE\nBUENOS AIRES,banco,0.935519
8,544832,Embargo - usuario,Embargo,562,30-99903208-3,CUIT,0.527177
9,546230,Embargo - usuario,Embargo,1542,JUZGADO CIVIL 7,juzgado,0.590764
10,546230,Embargo - usuario,Embargo,1542,40471/2023,expediente,0.544367
11,546230,Embargo - usuario,Embargo,1542,expte n* 40471/2023,expediente,0.720688
12,546230,Embargo - usuario,Embargo,1542,Juzgado Nacional de Primera Instancia en lo Ci...,juzgado,0.803238
13,546230,Embargo - usuario,Embargo,1542,jncivil7Opjn.gov.ar,email,0.993556
14,546230,Embargo - usuario,Embargo,1542,PESOS UN MILLON QUINIENTOS MIL,monto,0.570013
15,546230,Embargo - usuario,Embargo,1542,$1.500.000,monto,0.656647
16,546230,Embargo - usuario,Embargo,1542,"Banco\nde la Nación Argentina, Sucursal Tribun...",banco,0.945156
17,546230,Embargo - usuario,Embargo,1542,0110025950099897445578,CBU,0.983295
18,546230,Embargo - usuario,Embargo,1542,3 de diciembre de 2025,fecha,0.687914
19,543050,Embargo - usuario,Embargo,1470,JUZGADO DE FAMILIA N? 5 - SAN ISIDRO,juzgado,0.892531
20,543050,Embargo - usuario,Embargo,1470,20261011930Qnotificaciones.scba.gov.ar,destinatario,0.815372
21,543050,Embargo - usuario,Embargo,1470,13/3/2026,fecha,0.846929
22,543050,Embargo - usuario,Embargo,1470,Expte: SI - 38561 - 2022,expediente,0.682495
23,543050,Embargo - usuario,Embargo,1470,"Juzgado de Familia N* 5, Departamento Judicial...",juzgado,0.631902
24,543050,Embargo - usuario,Embargo,1470,juzfam5-siOjusbuenosaires.gov.ar,email,0.507267
25,543050,Embargo - usuario,Embargo,1470,0000003100087743731453,CVU,0.783683
26,543050,Embargo - usuario,Embargo,1470,$14.309.175,monto,0.800859
27,543050,Embargo - usuario,Embargo,1470,PESOS CATORCE MILLONES TRESCIENTOS NUEVE MIL C...,monto,0.549221
28,543050,Embargo - usuario,Embargo,1470,$7.200.000,monto,0.795342
29,543050,Embargo - usuario,Embargo,1470,PESOS SIETE MILLONES DOCIENTOS MIL,monto,0.588330
30,518820,Embargo - usuario,Embargo,1081,REZZET MA CIELO C/ GIECO ORLANDO MN,caratula,0.886669
31,518820,Embargo - usuario,Embargo,1081,Expte. N* 5013,expediente,0.882836
32,518820,Embargo - usuario,Embargo,1081,Tribunales,juzgado,0.712265
33,518820,Embargo - usuario,Embargo,1081,Cuenta N* 62-208\n0894723,cuenta judicial,0.771211
34,518820,Embargo - usuario,Embargo,1081,"04.11.2024, 09:32 hs.",fecha,0.844658
35,518820,Embargo - usuario,Embargo,1081,Orlando Jesús,persona embargada,0.591822
36,518820,Embargo - usuario,Embargo,1081,30-70308853-4,CUIT,0.592588
37,538081,Embargo - usuario,Embargo,1746,MERCADO PAGO ASSET MANAGEMENT S.A.,destinatario,0.883410
38,538081,Embargo - usuario,Embargo,1746,JUZGADO CIVIL Y COMERCIAL N* 10- MAR DEL\n\nPLATA,juzgado,0.841967
39,538081,Embargo - usuario,Embargo,1746,MERCADO PAGO ASSET MANAGEMENT S.A.,destinatario,0.889689
40,538081,Embargo - usuario,Embargo,1746,Expte. N* MP - 1493- 2026,expediente,0.762089
41,538081,Embargo - usuario,Embargo,1746,11/02/2026 13:01:47,fecha,0.760238
42,538081,Embargo - usuario,Embargo,1746,Mercado Libre SRL,destinatario,0.501680
43,522288,Embargo - usuario,Embargo,2655,20129293641,CUIT,0.561078
44,522288,Embargo - usuario,Embargo,2655,Expté.| NP 20280,expediente,0.824253
45,522288,Embargo - usuario,Embargo,2655,"Departamento Judicial d cedes\n(B], Secrétaría...",juzgado,0.865774
46,522288,Embargo - usuario,Embargo,2655,04/09/25,fecha,0.847663
47,522288,Embargo - usuario,Embargo,2655,28/10/25,fecha,0.668659
48,522288,Embargo - usuario,Embargo,2655,23-20026643-9,CUIT,0.650849
49,536721,Embargo - usuario,Embargo,1835,JUZGADO EN LO CIVIL Y COMERCIAL N? 4 - SAN NIC...,juzgado,0.854395

In [23]:
print("Cantidad de documentos procesados:")
print(df_entidades_embargos_muestra["id"].nunique())

print("\nCantidad total de entidades detectadas:")
print(df_entidades_embargos_muestra.shape[0])

print("\nEntidades por etiqueta:")
print(df_entidades_embargos_muestra["entidad_label"].value_counts())

print("\nScore promedio por etiqueta:")
print(
    df_entidades_embargos_muestra
    .groupby("entidad_label")["score"]
    .agg(["count", "mean", "min", "max"])
    .sort_values("mean", ascending=False)
)

Cantidad de documentos procesados:
10

Cantidad total de entidades detectadas:
72

Entidades por etiqueta:
entidad_label
juzgado              14
expediente           10
monto                 9
fecha                 9
destinatario          7
CUIT                  7
banco                 2
monto costas          2
DNI                   2
email                 2
persona embargada     2
cuenta judicial       2
empresa embargada     1
CBU                   1
CVU                   1
caratula              1
Name: count, dtype: int64

Score promedio por etiqueta:
                   count      mean       min       max
entidad_label
CBU                    1  0.983295  0.983295  0.983295
banco                  2  0.940338  0.935519  0.945156
empresa embargada      1  0.929711  0.929711  0.929711
caratula               1  0.886669  0.886669  0.886669
juzgado               14  0.811268  0.590764  0.966946
expediente            10  0.783782  0.544367  0.925378
CVU                    1  0.783683  0.783683  0.783683
email                  2  0.750411  0.507267  0.993556
fecha                  9  0.743223  0.545048  0.847663
cuenta judicial        2  0.716573  0.661935  0.771211
destinatario           7  0.666584  0.501680  0.889689
monto                  9  0.664685  0.522252  0.800859
DNI                    2  0.657817  0.527637  0.787998
CUIT                   7  0.646570  0.527177  0.884942
persona embargada      2  0.572489  0.553156  0.591822
monto costas           2  0.513562  0.508568  0.518556

**CONCLUSION**  
Se realizó una prueba inicial de GLiNER sobre 10 embargos. El modelo detectó 72 entidades, principalmente juzgados, expedientes, montos, fechas, destinatarios y CUIT. Las entidades más confiables fueron CBU, banco, empresa embargada, carátula, juzgado y expediente. Algunas etiquetas como persona embargada, monto costas y destinatario tuvieron scores más bajos, por lo que requieren revisión o ajuste de labels.

Probar GLiNER en **1 embargo corto, 1 promedio y 1 largo**

Esta prueba es clave. Sirve para ver si el rendimiento cambia según la longitud.

In [24]:
# Seleccionar un embargo corto, uno promedio y uno largo según cantidad de tokens

tokens_min = df_embargos["gliner_tokens"].min()
tokens_max = df_embargos["gliner_tokens"].max()
tokens_mediana = df_embargos["gliner_tokens"].median()

embargo_corto = df_embargos.loc[
    df_embargos["gliner_tokens"].idxmin()
]

embargo_largo = df_embargos.loc[
    df_embargos["gliner_tokens"].idxmax()
]

embargo_promedio = df_embargos.iloc[
    (df_embargos["gliner_tokens"] - tokens_mediana).abs().argsort().iloc[0]
]

df_prueba_longitud = pd.DataFrame([
    embargo_corto,
    embargo_promedio,
    embargo_largo
])

df_prueba_longitud[["id", "nombre", "clasificacion", "gliner_tokens", "largo_limpio"]]

         id             nombre clasificacion  gliner_tokens  largo_limpio
509  542136  Embargo - usuario       Embargo            149           285
588  544859  Embargo - usuario       Embargo           1055          3448
35   496830  Embargo - usuario       Embargo           3517         10926

Después corré GLiNER sobre esos 3:

In [31]:
def extraer_entidades_para_prueba(row, labels):
    text = str(row["texto_limpio"])

    entities = model.predict_entities(text, labels)

    resultados = []

    if len(entities) == 0:
        return [{
            "id": row["id"],
            "nombre": row["nombre"],
            "clasificacion": row["clasificacion"],
            "gliner_tokens": row["gliner_tokens"],
            "largo_limpio": row["largo_limpio"],
            "entidad_texto": None,
            "entidad_label": "SIN_ENTIDADES",
            "score": None
        }]

    for ent in entities:
        resultados.append({
            "id": row["id"],
            "nombre": row["nombre"],
            "clasificacion": row["clasificacion"],
            "gliner_tokens": row["gliner_tokens"],
            "largo_limpio": row["largo_limpio"],
            "entidad_texto": ent.get("text"),
            "entidad_label": ent.get("label"),
            "score": ent.get("score")
        })

    return resultados

In [32]:
resultados_longitud = []

for _, row in df_prueba_longitud.iterrows():
    resultados_longitud.extend(
        extraer_entidades_para_prueba(row, labels_embargo)
    )

df_entidades_por_longitud = pd.DataFrame(resultados_longitud)

df_entidades_por_longitud

/usr/local/lib/python3.12/dist-packages/gliner/data_processing/processor.py:417: UserWarning: Sentence of length 734 has been truncated to 384
  batch = [self.preprocess_example(b["tokenized_text"], b[key], class_to_ids) for b in batch_list]
/usr/local/lib/python3.12/dist-packages/gliner/data_processing/processor.py:417: UserWarning: Sentence of length 2542 has been truncated to 384
  batch = [self.preprocess_example(b["tokenized_text"], b[key], class_to_ids) for b in batch_list]

,id,nombre,clasificacion,gliner_tokens,largo_limpio,entidad_texto,entidad_label,score
0,542136,Embargo - usuario,Embargo,149,285,None,SIN_ENTIDADES,NaN
1,544859,Embargo - usuario,Embargo,1055,3448,CHEN FANG,persona embargada,0.596866
2,544859,Embargo - usuario,Embargo,1055,3448,Expte. 18132/2025,expediente,0.769912
3,544859,Embargo - usuario,Embargo,1055,3448,Juzgado Federal de Ejecuciones Fiscales Tribut...,juzgado,0.943470
4,544859,Embargo - usuario,Embargo,1055,3448,Dra. Patricia A.\nROTA,persona embargada,0.506305
5,544859,Embargo - usuario,Embargo,1055,3448,CHEN FANG,persona embargada,0.654965
6,544859,Embargo - usuario,Embargo,1055,3448,27-95308307-3,CUIT,0.787128
7,544859,Embargo - usuario,Embargo,1055,3448,CUIT N* 30-70308853-4,CUIT,0.541548
8,544859,Embargo - usuario,Embargo,1055,3448,MERCADOLIBRE S.R.L.,empresa embargada,0.520894
9,544859,Embargo - usuario,Embargo,1055,3448,CUIT N* 30-\n70308853-4,CUIT,0.624830
10,544859,Embargo - usuario,Embargo,1055,3448,"Banco de la\nNación Argentina, Sucursal Tribun...",banco,0.854469
11,544859,Embargo - usuario,Embargo,1055,3448,diez (10) días,plazo,0.936815
12,544859,Embargo - usuario,Embargo,1055,3448,17/11/2025,fecha,0.859339
13,496830,Embargo - usuario,Embargo,3517,10926,PODER JUDICIAL DE TUCUMÁN,juzgado,0.543861
14,496830,Embargo - usuario,Embargo,3517,10926,11 de diciembre de 2025,fecha,0.555013
15,496830,Embargo - usuario,Embargo,3517,10926,Expte. n?,expediente,0.904166
16,496830,Embargo - usuario,Embargo,3517,10926,Centro Judicial Capital,juzgado,0.688779
17,496830,Embargo - usuario,Embargo,3517,10926,PESOS TREINTA Y TRES\nQUINIENTOS MIL,monto,0.633721
18,496830,Embargo - usuario,Embargo,3517,10926,$33.500.000,monto,0.583418
19,496830,Embargo - usuario,Embargo,3517,10926,PESOS DIEZ\n\nBINCUENTA MIL,monto,0.643688
20,496830,Embargo - usuario,Embargo,3517,10926,CVU,CVU,0.753117

El mensaje:

```
Sentence of length 734 has been truncated to 384
Sentence of length 2542 has been truncated to 384
```

significa que GLiNER encontró fragmentos/oraciones demasiado largas y las recortó internamente a 384.

Es decir:

GLiNER no procesó completo ese fragmento largo. Lo cortó.

Esto es clave porque puede perder entidades que estén después del token 384 de ese fragmento. Por ejemplo, si el CBU, monto o persona embargada aparece más adelante, puede no detectarlo.

Resumen por documento:

In [27]:
df_entidades_por_longitud.groupby("id").agg(
    tokens=("gliner_tokens", "first"),
    entidades_detectadas=("entidad_texto", "count"),
    score_promedio=("score", "mean"),
    score_minimo=("score", "min"),
    score_maximo=("score", "max")
).sort_values("tokens")

,tokens,entidades_detectadas,score_promedio,score_minimo,score_maximo
id,,,,,
544859,1055,12,0.716379,0.506305,0.943470
496830,3517,8,0.663220,0.543861,0.904166

Y por etiqueta:

In [28]:
df_entidades_por_longitud.groupby(["id", "entidad_label"]).agg(
    cantidad=("entidad_texto", "count"),
    score_promedio=("score", "mean")
).reset_index().sort_values(["id", "cantidad"], ascending=[True, False])

        id      entidad_label  cantidad  score_promedio
4   496830              monto         3        0.620276
3   496830            juzgado         2        0.616320
0   496830                CVU         1        0.753117
1   496830         expediente         1        0.904166
2   496830              fecha         1        0.555013
5   544859               CUIT         3        0.651169
11  544859  persona embargada         3        0.586045
6   544859              banco         1        0.854469
7   544859  empresa embargada         1        0.520894
8   544859         expediente         1        0.769912
9   544859              fecha         1        0.859339
10  544859            juzgado         1        0.943470
12  544859              plazo         1        0.936815

PROBAMOS PORQUE NO APARECE INFORMACION DEL EMBARGO CORTO

Lo más probable es que el embargo corto no aparezca en df_entidades_por_longitud porque GLiNER no detectó ninguna entidad en ese documento. Como tu DataFrame de resultados se arma solo con entidades detectadas, si un documento no detecta nada, no aparece.

In [29]:
df_prueba_longitud[["id", "nombre", "gliner_tokens", "largo_limpio"]]

         id             nombre  gliner_tokens  largo_limpio
509  542136  Embargo - usuario            149           285
588  544859  Embargo - usuario           1055          3448
35   496830  Embargo - usuario           3517         10926

In [30]:
ids_prueba = set(df_prueba_longitud["id"])
ids_con_entidades = set(df_entidades_por_longitud["id"])

print("IDs probados:", ids_prueba)
print("IDs con entidades detectadas:", ids_con_entidades)
print("IDs sin entidades detectadas:", ids_prueba - ids_con_entidades)

IDs probados: {542136, 544859, 496830}
IDs con entidades detectadas: {544859, 496830}
IDs sin entidades detectadas: {542136}

**El embargo corto no tuvo entidades detectadas**

Como tiene solo 285 caracteres, probablemente no contiene suficiente contexto legal para detectar cosas como monto, CBU, juzgado, expediente, etc.

In [7]:
row_corto = df_embargos[df_embargos["id"] == 542136].iloc[0]

print(row_corto["texto_limpio"])

q a ZA mercad
A Ó-—
tArñ20190D 198

POMADA

40 007. vol sh oben Wisnewslal ssobañb" Wbiscineua y lorinoo lo

Bm 3 me DATE bs D ADA

ln MOO .1 7 alansoro.o
dm y o PrRMOONS 02 |

r ' As
1
4 |
a
1
y
!
y €
S á .
ÑN
ba 5 ' |
Í
4
1]
|
otr y" i |
Sl Na?
|
, '
1. A |
|
rra NO] | |
yiv! 31 | |

El embargo corto seleccionado para la prueba tenía 149 tokens y 285 caracteres, pero al revisar su contenido se observó que el OCR era ilegible. El texto no contenía entidades legales reconocibles como expediente, juzgado, persona embargada, monto, CUIT, CBU o banco. Por ese motivo, GLiNER no detectó entidades.

Este caso muestra que la longitud del texto no es suficiente para determinar si un documento es útil. Además de textos vacíos, errores de descarga o textos muy cortos, es necesario considerar una categoría de baja calidad OCR para textos que tienen contenido, pero no son interpretables.

## Conclusión de la prueba con GLiNER por longitud de documento

Se realizó una prueba inicial de extracción de entidades con GLiNER sobre embargos de distinta longitud, tomando como referencia la cantidad de tokens calculada con el tokenizer del modelo.

En la exploración general del dataset de embargos se observó que existen 627 documentos, con una media de 1128 tokens, un mínimo de 149 tokens y un máximo de 3517 tokens. Esto indica que la mayoría de los embargos tiene una longitud manejable, aunque existen casos considerablemente más extensos.

En la prueba por longitud, GLiNER detectó entidades relevantes en documentos de tamaño medio y largo, como expediente, juzgado, CUIT, montos, banco, fecha, plazo y persona embargada. Sin embargo, durante la ejecución aparecieron advertencias indicando que algunas secuencias fueron truncadas a 384. Esto significa que GLiNER no procesó completamente ciertos fragmentos largos del texto.

El documento de tamaño medio analizado presentó 1055 tokens, 12 entidades detectadas y un score promedio aproximado de 0.716. El documento largo presentó 3517 tokens, 8 entidades detectadas y un score promedio aproximado de 0.663. Esta diferencia sugiere que, en textos más largos, la calidad de extracción puede disminuir y existe riesgo de pérdida de entidades por truncamiento.

Como conclusión, GLiNER resulta útil para una primera extracción de entidades en embargos, pero antes de aplicarlo sobre la totalidad de los documentos conviene implementar o probar una estrategia de división del texto en fragmentos más pequeños. Esto permitiría evitar truncamientos y mejorar la cobertura de entidades en documentos largos.

## Conclusión de la prueba corto / promedio / largo

Se probaron tres embargos con distinta longitud para observar cómo responde GLiNER según la cantidad de tokens.

El embargo corto, con 149 tokens y 285 caracteres, no generó entidades detectadas. Esto puede deberse a que el texto es demasiado breve, contiene poca información legal útil o no incluye entidades compatibles con las etiquetas definidas.

El embargo de longitud media, con 1055 tokens, generó 12 entidades detectadas y un score promedio de aproximadamente 0.716. Este resultado indica que GLiNER puede funcionar razonablemente bien en documentos de tamaño medio.

El embargo largo, con 3517 tokens, generó 8 entidades detectadas y un score promedio de aproximadamente 0.663. Sin embargo, durante la ejecución apareció una advertencia de truncamiento, indicando que una secuencia larga fue recortada internamente a 384. Esto implica riesgo de pérdida de información en documentos extensos.

Como conclusión, GLiNER muestra resultados útiles para una primera extracción de entidades en embargos, pero los documentos largos requieren una estrategia adicional, como dividir el texto en fragmentos más pequeños antes de procesarlo.